### ISSUE TITLE
[@mantine/core] Missing TS types in v1.3.0

### ISSUE THREAD

**Issue by steschwa** [mantinedev/mantine#112]
After installing `@mantine/core@1.3.0` my IDE complained about missing TS types. After a quick look into `node_modules/@mantine/core/package.json` i saw that types are declared in `package.json` 
(`"types": "lib/src/index.d.ts"`) but do not exist.

![Mantine TS types missing](https://user-images.githubusercontent.com/24265130/120538582-fb3e7180-c3e6-11eb-825d-9fd8b880a5c6.png)

I've checked the package contents from npmjs.com (https://registry.npmjs.org/@mantine/core/-/core-1.3.0.tgz) and the typings are not included.

Also when cloning the repo and building `mantine-core` locally, it generates all typings as expected 🤷‍♂️

Can you please confirm and update the NPM package?

Great job with Mantine! First component library i really enjoy using without exceptions

**Comment by rtivital** [comment]
Hi Stefan, thanks for feedback and reporting the issue, I've published version 1.3.1 that should include types, can you verify that it works for you?

The problem was in [.npmignore](https://github.com/mantinedev/mantine/commit/d097e4477de9b7eb96f6740c12a216b658410ff2) file, turns out `src` ignore also removes `lib/src` files and types were not published to npm

**Comment by steschwa** [comment]
Wow thanks for fast reply + fix.

Types are included and VSCode is happy 🥳
