### ISSUE TITLE
Remove generics from pass through components

### ISSUE THREAD

**Issue by rtivital** [mantinedev/mantine#119]
Currently components that allow changing root element with `component` prop require generic types to work:

```tsx
<Button<"a", HTMLAnchorElement>
  component="a"
  href="https://mantine.dev"
  onClick={(event) => event.preventDefault()}
  elementRef={node => console.log(node)}
>
  Mantine
</Button>
```

First generic type resolves to `React.ComponentPropsWIthoutRef<'a'>` and second to `{ elementRef: React.ForwardedRef<HTMLAnchorElement> }`.

It brings some confusion and will be much better if first argument can be omitted (ref type can still be done via generic):

```tsx
// without elementRef
<Button
  component="a"
  href="https://mantine.dev"
  onClick={(event) => event.preventDefault()}
>
  Mantine
</Button>

// with elementRef
<Button<HTMLAnchorElement>
  component="a"
  href="https://mantine.dev"
  onClick={(event) => event.preventDefault()}
  elementRef={node => console.log(node)}
>
  Mantine
</Button>
```

Resources:
-  [ComponentPassThough type](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/types.ts)
- [Button component used in example](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Button/Button.tsx)

**Comment by Kukkimonsuta** [comment]
This may be completely useless, but playing with super simplified case around types and `ComponentPassThrough` it may be possible to preserve the types properly if we can change things up a bit. I'll investigate further in coming days and report back, for now let me just drop playground here:

[TypeScript playground](https://www.typescriptlang.org/play?experimentalDecorators=false&emitDecoratorMetadata=false&ts=4.3.5#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4Aoc4AOxiSk3STgGFdJqlaB5MGYCNQA8AFThIAHnWoATAM6JiMAHQBRADZIQXGCICeYJAD44Ab3Jw4AegBUNuBq0640OGnaDnMABYp4Ad2B1dTgAI2YAVzkkGTgUBRwIeCRNbVo4GysLNw9OWgB+AC44EQoAX0oaOgYmVlydZExRcSkueUV0FUc03QNjM2zbe0b6LjRmGAhxVOdXd3BPdJ8-OEDgsMjo2Pi4ROSZ9Mzs+Y4GpEwijoxlADFofxQoGRjGoWROtQOYV5EjI3LKrR6IxxnAAEIRGCTahg+JIAAKODACnMliG4Mh0LgMD6cShUGAoUhzCOlhxhku+DkEVCIGAMHwcAAPgQiVDBIyWYQkNEGQDyJgItQMAJqBj2cIxJJpO13tdujp9IY4ABeVmYjlGAAUphyCzyMAANHrTrRGsa0N4gjIiGKysU5SpERBkQB1eneFhW9Q2rhCCES2HRZ3IuAAMjq+p0vH4glEJgjbCjZvO8aMAEoBpZ3NQ5PAFek1SdFvB8vl1RKyJRLEQYBEoGKtdlLEICzAjM3LGZLdbbRUu3AhFY2x3LOn+YLhbGxSIeTAbkKRYIUOok6aYFrM6jdkg6w3BzJgAA3IxDw8n-k5vMlOd3KAPJ6NBdT0Urtcl1VXFSYe6PGSvAAJEQAFkABkABFjzbY0hQAa2oCB-GobUtTAJE5GNIhMEzFUTG3Wt6zFIRzx3TAVVMLCylPKxz3+cgynHSgr3geIA2hABJcB1GANB6U-f0NTFYsDUaciJFVEwrwgTRlHUCAAHMtQkdMqKHNjBDo5i4jkdTqFUCQwG43j4DVASJRNEsVQAIjZaErIskTzjEiSclzaSkFkhSlJU6jdM0wRr3iABBfjdIcnRrPPezhLOMjTHE3DXLkdzPMU5TVKsPyKC0+JIKPULBPC2hIuPaL6hTOKEskgKUrktKfLUwT-NzFi5GfJdqDfcqTMHMKYuK0xZzzdrpy65MYDKIrvic+KXKkmS6u8jKsvIHK2t-R9zhG19V26grzP6mByKG+cNv-LbF1G3bxsmw7RNmxL5o8xb0t8pqKCAA)

**Comment by rtivital** [comment]
Looks promising, if you will be able to fix the issue with missing types as well (#159) it would be great

**Comment by Kukkimonsuta** [comment]
Turns out that was indeed mostly useless, but it lead me to possible solution here https://github.com/microsoft/TypeScript/issues/43717

Basically the function needs to look like this:

```ts
// based on https://github.com/microsoft/TypeScript/issues/43717#issuecomment-821942083
type Join<T, U> = T & Omit<U, keyof T>;

export type ComponentPassThrough<T extends React.ElementType, Props> = Props &
  Join<{
    /** Element or component that will be used as root element */
    component?: T;
  }, React.ComponentPropsWithoutRef<T>>;

```

This gets rid of the `any`, however uncovers another issue where you can't assign the default element due to perceived type mismatch. There are two ways to go from there:

1. move the default value to body https://github.com/Kukkimonsuta/mantine/commit/f13243c66f70340bff2395655dcbf8710c683f5b
2. pass down the default type to `ComponentPassThrough` as well https://github.com/Kukkimonsuta/mantine/commit/ea5bc27fd9bb7962cb4b5b0c9be64318c56b25d8

I personally prefer 1. but I'll leave it to you to decide the style - functionally they should be the same. Please let me know which would be your choice and I'll continue working on this.

--------------

The second generic argument can be safely removed it seems, since you can get the type by using `React.ElementRef<T>`. Would it be reasonable to simply extend `ComponentPassThrough` and implement `elementRef` logic on all components using it? For instance there isn't way to get ref on `Overlay`. It would look roughly like this (and perhaps for 3.0 it might be good idea to sync the naming `component + componentRef` or `element + elementRef`).

```ts
export type ComponentPassThrough<T extends React.ElementType, Props> = Props &
  Join<{
    /** Element or component that will be used as root element */
    component?: T;
    /** Get root element ref */
    elementRef?: React.ForwardedRef<React.ElementRef<T>>;
  }, React.ComponentPropsWithoutRef<T>>;
```

**Comment by rtivital** [comment]
I've found similar thing in reach ui – https://github.com/reach/reach-ui/blob/develop/packages/utils/src/polymorphic.ts#L32
Haven't explored it yet as it seems pretty complicated but all their components work without generic types because of hardcoded element type – https://github.com/reach/reach-ui/blob/main/packages/accordion/src/index.tsx#L206

**Comment by rtivital** [comment]
I've decided to leave it as is but with another implementation which has better types support, see example – https://github.com/mantinedev/mantine/blob/next-minor/src/mantine-core/src/components/Text/Text.tsx

**Comment by passionkind** [comment]
I've spent the past 3 days trying to figure out how one can use a generic component with proper ref usage. Insane 😂

One link you posted (reach-ui adaption) kinda worked, but not for generic components. Then I found some more ideas here https://stackoverflow.com/a/58473012 . And then I've been curious from day one when I read about mantine, why you had been using `elementRef` instead of `ref`. Meanwhile I believe I know the reasons.

However, I also found a solution that borrows from several solutions and works properly with generics and our `elementRef`.

Instead of posting the code, you can find a [working simple codesandbox sample here](https://codesandbox.io/s/optimistic-danilo-64xcz?file=/src/App.tsx)

Try modifying the components usage by
- changing `dependsOnSomething` to see that generics work
- hovering over the ref 
- change the type of preceding `useRef<>`
- changing the `as` property or removing it
- add an onClickHandler and check the event type

```tsx
<MyComponent
        style={{ backgroundColor: "black", color: "white" }}
        as="audio"
        ref={ref}
        something="a"
        dependsOnSomething={true}
      >
        hello
      </MyComponent>
```

I'd assume, with minimal modifications, this should also work for how you're building components currently.

Would love to know your feedback!

**Comment by rtivital** [comment]
@passionkind thanks for sharing, it works great, I've tried it out with custom components and it works as well – https://tsplay.dev/WPjlYN

 Maybe I'll replace elementRef with ref in next release

**Comment by Kukkimonsuta** [comment]
@passionkind Very nice, I think it's pretty close to what my sample commits above do, there is however a problem in the solution - when the `as` prop is not specified and default is used, it only sort of works for events:

![image](https://user-images.githubusercontent.com/737093/135405019-3f6ffda7-b2df-4826-a3c8-ee53d47b6d5e.png)

Unfortunately I've been unable to find solution for that as well.

**Comment by passionkind** [comment]
@Kukkimonsuta @rtivital thank you for pointing mit towards the broken default!

I tried something else, based on the radix-ui/reach-ui approach and [another snippet I found for using forwardRef with generics](https://fettblog.eu/typescript-react-generic-forward-refs/).

So far it works fine with
- default
- as/component
- generics
- ref
- proper element types

Take a look here https://codesandbox.io/s/elastic-taussig-zw64c

I don't know if that has any impacts on displayName etc. (read somewhere about it). But it seems to be the only way to use forwardRef in conjunction with generics. It's casted, but from what I read so far, it just seems to be technically impossible to use generics with forwardRef without casting and in the end, I don't mind writing my props on top or below the function.

If I don't use `React.createElement` but JSX instead, TypeScript, at least in the TS Playground complains about a too complex object. So either we cast the component again from `As` to the default or use React.createElement.

The prop determination could be further simplified as we basically only need the props of the radix/reach type helper and not the whole component.

Please let me know what you think.

**Comment by Kukkimonsuta** [comment]
The cast there sucks, but it's probably the best solution for end user of the components. Might worth trying to find minimum reproduction code and try filing issue on <https://github.com/microsoft/typescript> if there isn't one already.

**Comment by passionkind** [comment]
@Kukkimonsuta I know. I'd also prefer to avoid casting. 

There is an npm package that tries to achieve something similar. Although generics don't work with it again. Here's the package https://www.npmjs.com/package/react-polymorphic-types

And here are some further links that cover the issues:
- https://github.com/microsoft/TypeScript/issues/30134 
- https://twitter.com/jaredpalmer/status/1217149616082296833?lang=en

There was another issue in the TypeScript repo that more clearly explained why it doesn't (yet) work. Anders Hejlsberg commented that it would be doable but not trivial. Although I cannot find that discussion anymore. Think I stumbled upon it through that discussion on twitter by @jaredpalmer

**Comment by zeestack** [comment]
I am having type clashes when I pass the button or any polymorphic component to higher order component.

React.ComponentType<T> is not assignable to Mantine's polymorphic component. One solution to mark the type to any, if I do this I loose the types.

How can we simplify types a bit ....

**Comment by douglasg14b** [comment]
@zeestack Did you ever solve this issue? I'm running into the same.

**Comment by AndrejGajdos** [comment]
I have the same issue. Are there any solutions for supporting this use case in Typescript?
