### ISSUE TITLE
Improve Pagination accessibility

### ISSUE THREAD

**Issue by andresmanz** [mantinedev/mantine#1414]
Suggestions:
- Place pagination in `<nav>` (or set `role="navigation"`) and add `aria-label="pagination" `
- Indicate current page button by adding `aria-current="page"`

This would improve the current defaults and make testing easier. Some resources (not sure what's a good one): [w3.org](https://design-system.w3.org/components/pagination.html) / [a11y-style-guide.com](https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination) / [a11ymatters.com](https://www.a11ymatters.com/pattern/pagination/)

**Comment by wes337** [comment]
We shouldn't hard-code `aria-label="pagination"` in, because not all uses for this component will be in English.

We could just add `role="navigation"` _(role does not need translations)_, and then have another optional prop `ariaLabel`, which could be defined as needed when implementing this component.
