### ISSUE TITLE
pop-top-left and pop-top-right transitions not working as expected?

### ISSUE THREAD

**Issue by blake-epistemix** [mantinedev/mantine#1657]
### What package has an issue

@mantine/core

### Describe the bug

If you check out the Transition component page (https://mantine.dev/core/transition/) the pop-top-left and pop-top-right still appear to be "popping" from the bottom. I was having the same issue when trying to customize the Menu component.

### In which browser did the problem occur

All

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/transition/

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
All pop-* transitions implement the same animation, the only different prop in them is transform-origin, they work as expected

**Comment by Narcha** [comment]
I encountered the same issue. This appears to be caused by the inclusion of a `translateY(...)` part in the `transform` property.
Some relevant code:
https://github.com/mantinedev/mantine/blob/76067581d2797570eb2ce77a1665398955b25c7d/src/mantine-core/src/components/Transition/transitions.ts#L32-L36
https://github.com/mantinedev/mantine/blob/76067581d2797570eb2ce77a1665398955b25c7d/src/mantine-core/src/components/Transition/transitions.ts#L137-L145

When manually recreating the affected transitions without the `translateY()`, the issue disappears. This is how I ended up fixing it in my code:
```tsx
<Menu
  position="bottom-end"
  transitionProps={{
    transition: {
      in: { opacity: 1, transform: "scale(1)" },
      out: { opacity: 0, transform: "scale(.9)" },
      common: { transformOrigin: "top right" },
      transitionProperty: "transform, opacity",
    },
  }}>
```
