### ISSUE TITLE
Spoiler doesn't render label when inside Accordion.Item

### ISSUE THREAD

**Issue by mateuszdziuba** [mantinedev/mantine#1811]
### What package has an issue

@mantine/core

### Describe the bug

When placed inside Accordion component Spoiler component won't render labels, making it uncontrollable.

### In which browser did the problem occur

Chrome, Firefox

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/cocky-jang-yfobyv?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by khobiziilyes** [comment]
**Your content is just not long enough:**
https://codesandbox.io/s/affectionate-hugle-xiy1qf

**Comment by lawff** [comment]
> Still doesn't work for me. I think it might be related to this issue with spoiler and collapse #1158

Yes, they are the same problem, the Collapse 'display: none' leading to the Spoiler content clientHeight to 0, so not show the label.

**Comment by wes337** [comment]
I believe this is caused because we are setting the max height of the Spoiler component using its own offset height (which is 0 when collapsed inside the accordion).

It's checked in the useEffect on line 65 of the Spoiler component. It's calculated when the Spoiler component mounts and when the content updates (but not when you expand/collapse the Accordion).
