### ISSUE TITLE
Head title differs from actual title on page refresh

### ISSUE THREAD

**Issue by Bladeyy** [mantinedev/mantine#2099]
### Link to the page where something nasty is located

https://mantine.dev/

### Exact quote of what is wrong

I'm not sure but when I try to refresh the website head title shows **Appshell demo | Mantine** for a split second before changing back to Mantine. Also the white flashing can it be stopped on page refresh? Persist dark mode on page refresh just like how next-themes package does. 

I have attached a file showing this.

https://user-images.githubusercontent.com/40533936/184469657-1d177f4b-19f3-4797-ab6c-ad99d113fe4e.mp4

Also thanks for making this beautiful library. Learned a lot from the documentation.

**Comment by rtivital** [comment]
Hi @Bladeyy, thanks for reporting an issue, it comes from gatsby and I do not really think that we should waste time fixing it. If you want to submit a PR with a fix, then feel free to do so, otherwise let's keep it as is as it's not major. You can find information about color scheme switching here – #1584

**Comment by Bladeyy** [comment]
No problem @rtivital. Agree that's not a major issue as there are 3rd party plugins to solve it.
