### ISSUE TITLE
Select component restores text if deleted

### ISSUE THREAD

**Issue by jfilby** [mantinedev/mantine#2101]
### What package has an issue

@mantine/core

### Describe the bug

When an item is chosen in a Select component, delete the text and put the focus somewhere else, the deleted text returns. I want to be able to clear what was selected.

For example I highlight the text and press the delete key and then the tab key to move to the next component.

This can be quickly reproduced on the Select component page in the given examples, e.g. the choose the employee of the month example: https://mantine.dev/core/select/

### What version of @mantine/hooks page do you have in package.json?

5.1.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It is expected behavior, select works with a set of options and does not support free input – value that is displayed in the input always matches current selected item. If you need free input support, use Autocomplete component instead. You can also subscribe to Select search change with `onSearchChange` prop and manage value on your side if you still want to use Select component.
