### ISSUE TITLE
Long Text in `use-debounced-value` hook's playground enables horizontal scroll

### ISSUE THREAD

**Issue by PhantomKnight287** [mantinedev/mantine#2165]
### Link to the page where something nasty is located

https://mantine.dev/hooks/use-debounced-value/

### Exact quote of what is wrong

If you type something very long in the Input box, the text will overflow the container and page resulting in a horizontal scroll.
Example:
![image](https://user-images.githubusercontent.com/76196237/185576172-b60199f4-8b8f-4e2f-a91d-e7613d45c976.png)

**Comment by ryuhangyeong** [comment]
## Issue

#2165

## Description

When I looked into this problem, I thought it was a problem with the Text component rather than the fault of Mantine's documentation.

In addition to the page mentioned in the issue, the same thing happens to all other pages that use the Text component.

### Card

https://mantine.dev/core/card/

![image](https://user-images.githubusercontent.com/27342882/185605886-f8701bd1-7b2b-4cf7-b40f-f789c472b41a.png)

https://mantine.dev/core/text/

![image](https://user-images.githubusercontent.com/27342882/185606184-cd152611-17d3-4f93-adcc-3e73c07a6e6c.png)

## Result

To solve this problem, there may be a way to receive `word-break` as a prop in the Text component. Or set the default to break-all and you're done!

Which method do you think is better?

**Comment by rtivital** [comment]
The issue is with use-debounce demo only, Text component works as expected

**Comment by ryuhangyeong** [comment]
OK

**Comment by wes337** [comment]
Just add `overflow-wrap: break-word;` to the div wrapper in the "usage" demo:
![image](https://user-images.githubusercontent.com/9464690/185763849-52ab0dcb-94a9-4d1d-88fe-a87262eabde4.png)

**Comment by ryuhangyeong** [comment]
@wes337 Thank you. I will write a PR based on your advice.
