### ISSUE TITLE
SpotLight actions state not properly changing

### ISSUE THREAD

**Issue by foxxycodes** [mantinedev/mantine#2201]
### What package has an issue

@mantine/spotlight

### Describe the bug

While dynamically changing `actions` via `registerActions` does not change the `actions` returned from the `use-spotlight`-hook.
I think the issue here might be, that I'm calling `removeActions` and right after `registerActions`...

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### If possible, please include a link to a codesandbox with the reproduced problem

[CodeSandbox](https://codesandbox.io/s/patient-bash-by1ko0?file=/src/SpotlightButton.tsx)

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @foxxycodes, please provide an example of code that causes the issue

**Comment by foxxycodes** [comment]
> Hi @foxxycodes, please provide an example of code that causes the issue

Hi @rtivital, I added an example.

**Comment by Hyper-Development** [comment]
@foxxycodes @rtivital I have the same issue.

**Comment by foxxycodes** [comment]
I think the problem is not directly related to the `SpotLight` itself, but rather on how to work with it when trying to create `actions` dynamically. As of this reason, I will close whis issue.

**Comment by grezzzy** [comment]
Was there a recommendation for how to proceed with bulk action updates. In our production app, we are attempting to load a large list of actions that are dependent on when a user opens a panel. I would have assumed `removeActions` and then `registerActions` is the best way to accomplish this since there is no function to entirely replace all actions at once. But as mentioned above, this does not seem to be easy to do in Mantine and never actually deletes the prior actions.

**Comment by rtivital** [comment]
In 6.0 actions are fully controlled – https://mantine.dev/others/spotlight/#controlled-query
