### ISSUE TITLE
use-window-scroll

### ISSUE THREAD

**Issue by meel-hd** [mantinedev/mantine#2303]
### What package has an issue

@mantine/hooks

### Describe the bug

Just importing this hook makes the window scroll bar on the left not smooth.

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### Possible fix

probably a way to choose the type of the scroll behavior, or by default the scroll should be smooth.

**Comment by rtivital** [comment]
> Just importing this hook makes the window scroll bar on the left not smooth.

If you import and do not use the hook, then it does not really do anything as events are attached to window object. Please provide two sandboxes: one that will show correct behavior and one that shows incorrect behavior.

**Comment by rtivital** [comment]
Please provide two sandboxes: one that will show correct behavior and one that shows incorrect behavior.

**Comment by icflorescu** [comment]
I just used `use-window-scroll` on [the docs website](https://icflorescu.github.io/mantine-datatable/getting-started) of Mantine DataTable to add a subtle header shadow when paged is scrolled down and I can confirm there's nothing wrong with the hook itself.

@meel-hd - perhaps the problem lies somewhere else in your application?

**Comment by rtivital** [comment]
I do not think that the issue is with Mantine, @meel-hd feel free to reopen the issue if you can provide a reproduction.
