### ISSUE TITLE
Menu.Dropdown not placed near Menu.Target when inside a scaled element

### ISSUE THREAD

**Issue by adam-binks** [mantinedev/mantine#2314]
### What package has an issue

@mantine/core

### Describe the bug

Example (menu dropdown with item "Delete" is far from the overflow dropdown. Inside a react-pinch-pan-zoom TranformComponent, which applies transform: scale(n).

<img width="131" alt="image" src="https://user-images.githubusercontent.com/13518594/187923160-4668bb40-e62c-48a1-b834-8360d7158f92.png">

### What version of @mantine/hooks page do you have in package.json?

5.2.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @adam-binks, Menu and other similar overlay components are built with floating ui, we cannot support that until floating ui provides this feature. If you want to find out more, you can open discussion in Floating UI repository – https://github.com/floating-ui/floating-ui/discussions

**Comment by rtivital** [comment]
I would say that it is expected behavior – you can apply any kinds of transforms to an element (`skew`, `rotate`, `scale`, `translate`) and those transforms do not impact element size – it still takes the same amount of space. I doubt that it is possible to position floating part correctly with all these transforms, so I would not really expect from floating ui to support this feature.
