### ISSUE TITLE
Modal overlay is rendered above the scroll

### ISSUE THREAD

**Issue by italodeandra** [mantinedev/mantine#2371]
### What package has an issue

@mantine/modals

### Describe the bug

![image](https://user-images.githubusercontent.com/19225266/188698570-4b97fb7a-f2c4-4e9e-88aa-d6459fd667ab.png)

You can scroll normally using the mouse scroll, but if you try clicking the scroll bar you actually click the overlay triggering the modal to close.

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/others/modals/

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
@italodeandra feel free to send a PR with a fix

**Comment by rtivital** [comment]
Help is still wanted on this, if someone wants to submit a PR feel free to ping me here.

**Comment by IdrisIsra** [comment]
@rtivital I think I have a fix, please review PR.

**Comment by rtivital** [comment]
Issue is not fixed, #2445 is not a valid solution as click outside events do not work

**Comment by IdrisIsra** [comment]
My bad, didn't notice that issue.

I'm kind of at a loss, any ideas? The only thing I can think of right now is to change the inset of the overlay so that it does not cover the scrollbar to the right, but this would need to be mirrored in RTL situations and it would also only need to not do this on mobile resolutions. As far as I know there's no way to give position: absolute to the scrollbar to make it have priority, and I'm not sure if putting a transform on it to move it up would be a good idea. Maybe something that I don't know?

**Comment by armanatz** [comment]
@rtivital I was facing the same problem and I believe I fixed it with my PR #2669
