### ISSUE TITLE
Allow SelectItem to have a value of number

### ISSUE THREAD

**Issue by mmahalwy** [mantinedev/mantine#2383]
### What package has an issue

@mantine/core

### Describe the bug

Currently TS does not allow value on `SelectItem` to be anything but `string`. 

See: https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Select/types.ts#L11

### What version of @mantine/hooks page do you have in package.json?

5

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Allow `SelectItem` to accept the same options as `<option />`. See:

```ts
interface OptionHTMLAttributes<T> extends HTMLAttributes<T> {
        disabled?: boolean | undefined;
        label?: string | undefined;
        selected?: boolean | undefined;
        value?: string | ReadonlyArray<string> | number | undefined;
    }
```

**Comment by rtivital** [comment]
Hi @mmahalwy, Select does not support values apart from strings because it:
- is how native select element works
- is much easier to maintain
- can produce all sorts of issues if we decide to support non-primitive values

Select and other similar components are already pretty complex, and I would rather not waste a lot of time maintaining this feature.
