### ISSUE TITLE
[Pagination] Text overlapping

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#251]
Hi, 
I have a problem with the new `Pagination` component when the total amount of pages is large?
Text

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)? 
**@mantine/core**
- What package version are you using? 
**2.5.0**
- In which browser and operating system issue occurred?  
**Chrome, macOS**

![image](https://user-images.githubusercontent.com/4768095/133654839-944a319a-081d-42f9-a381-9e39f5606b88.png)

**Comment by rtivital** [comment]
Hi @nghiepit thanks for reporting
@EmilMalanczak do you want to work on this issue?

**Comment by EmilMalanczak** [comment]
Sure, I know what's the issue here. The `width` of each item is static (16px if I good remember). A possible solution is to change `width` to `min-width` and will solve that case since in larger it will simply expand. 

Are you ok with that @rtivital? I'll provide a quick fix tomorrow after finishing my job

**Comment by rtivital** [comment]
Yep, sounds good, please also add some padding so that it does not look too tight

**Comment by rtivital** [comment]
Since there was another issue with pagination, I've fixed that myself, it should work fine in 2.5.1
