### ISSUE TITLE
List.Item overflows List 

### ISSUE THREAD

**Issue by edymusajev** [mantinedev/mantine#2778]
### What package has an issue

@mantine/core

### Describe the bug

The itemWrapper div inside of `List.Item` overflows the width of the List. 
<img width="612" alt="Screenshot 2022-10-24 at 00 04 54" src="https://user-images.githubusercontent.com/9220737/197405465-cca9d96f-da84-4dfc-ba4b-b4d861738507.png">

### What version of @mantine/hooks page do you have in package.json?

5.6.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/relaxed-matan-upqijw

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by koralarts** [comment]
@rtivital I'd like to help take a look at this.

**Comment by koralarts** [comment]
Did a little research about why this is happening. From what I researched, `list-style-position: inside` is handled differently by different browsers according to ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position)). After checking different browsers (Chrome, Safari, Firefox, and Edge) they seem to act the same.

**Quick Solution**

A quick solution is to pass a custom bullet icon.

```javascript
<List icon="•"> ... </List>
```

---

**Caveat(s)**

The `::marker` element is controlled by having an element have `display: list-item`.

**Possible Solutions**

1. Calculate the width of the item wrapper to take into account the bullet. This by default isn't a good solution since sizing won't be consistent between browsers.
2. Use a custom bullet. This can be done in multiple ways -- via CSS or custom element.

**2.1 CSS**

A custom bullet can be created using a `::before` element. I used `display: list-item` instead of passing a bullet in `content` because it will render the bullet using the browser's preferred bullet.

```css
li {
  display: flex;
  
  &::before {
    content: ' ';
    display: list-item;
  }
}
```

https://codesandbox.io/s/mantine-list-item-overflow-4n19br?file=/src/App.tsx

**2.2 Custom Element**

A custom element rendering a bullet could be the default element rendered if `icon` is not passed.

---

I think either solution would be the least invasive as both won't require breaking structural changes. If we feel one is a viable solution, I can make a PR with the selected solution; otherwise, we'll brainstorm another solution.

**Comment by Manas-Nagelia** [comment]
A more straightforward solution is to add <span> tags inside the <List.Item> tag. This is because this commit with removed the original <span> tags causing this overflow to happen: #2146

**Comment by 4m1n83** [comment]
@koralarts  you are right!
Here is a codepen that shows the error: https://codepen.io/aminbe/pen/dygmoge
There is no perfect solution for this one ...
I propose removing the `listStylePosition: 'inside',` and then adjust padding:

```export default createStyles(
  (theme, { withPadding, listStyleType }: ListStylesParams, { size }) => ({
    root: {
      ...theme.fn.fontStyles(),
      listStyleType,
      color: theme.colorScheme === 'dark' ? theme.colors.dark[0] : theme.black,
      fontSize: getSize({ size, sizes: theme.fontSizes }),
      lineHeight: theme.lineHeight,
      margin: 0,
      paddingLeft: withPadding ? rem(40) : theme.spacing.sm,
    },
  })
);```

What do you think?

What do you think?

**Comment by Manas-Nagelia** [comment]
> @koralarts you are right! Here is a codepen that shows the error: https://codepen.io/aminbe/pen/dygmoge There is no perfect solution for this one ... I propose removing the `listStylePosition: 'inside',` and then adjust padding:
> 
> ```
>   (theme, { withPadding, listStyleType }: ListStylesParams, { size }) => ({
>     root: {
>       ...theme.fn.fontStyles(),
>       listStyleType,
>       color: theme.colorScheme === 'dark' ? theme.colors.dark[0] : theme.black,
>       fontSize: getSize({ size, sizes: theme.fontSizes }),
>       lineHeight: theme.lineHeight,
>       margin: 0,
>       paddingLeft: withPadding ? rem(40) : theme.spacing.sm,
>     },
>   })
> );```
> 
> What do you think?
> 
> What do you think?
> ```

I made a Pull Request and it got merged, so the issue should be fixed.

**Comment by Manas-Nagelia** [comment]
https://github.com/mantinedev/mantine/pull/2857
