### ISSUE TITLE
openModal /openContextModal causes error when ModalSettings contain id

### ISSUE THREAD

**Issue by fernandes77** [mantinedev/mantine#3393]
### What package has an issue

@mantine/modals

### Describe the bug

When using `openModal` or `openContextModal` and providing an object that contains an `id`, this happens:

<img width="1280" alt="2023-01-18_12-57" src="https://user-images.githubusercontent.com/48812482/213225945-05f10f92-9891-4c5d-b4b8-7ea89d750416.png">

### What version of @mantine/hooks page do you have in package.json?

5.9.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/tender-thunder-22hkgx?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It is issue with React 18, I do not know how to fix it. Just do not use `id`.

**Comment by cyantree** [comment]
Did you possible mean to pass `modalId` instead of `id`?

Besides that I think this is a bug (or a too loose behaviour) in `useId()`:
https://github.com/mantinedev/mantine/blob/master/src/mantine-hooks/src/use-id/use-id.ts#L25

In this line there's a condition that may lead to a varying hook exeuction in case the argument changes.

The hook is used here:
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Modal/Modal.tsx#L173

So when the modal provider initializes it renders the modal with `id: undefined` and calls the hook as `useId(undefined)`. On opening your modal with `id: 'test'` the hook gets called as `useId('test')` and therefore switches to the other execution mode.

IMHO the first step may be to specify whether the first argument passed to `useId()` is allowed to change. If yes then it should be made sure that always the same hooks get executed. If not the user should be warned.

**Comment by rtivital** [comment]
Fixed in 6.0 – https://codesandbox.io/s/modal-with-id-error-forked-qxbi35?file=/src/App.tsx
