### ISSUE TITLE
Major layout shifts with next@13.1.1

### ISSUE THREAD

**Issue by avkash1** [mantinedev/mantine#3440]
### What package has an issue

@mantine/core

### Describe the bug

Hello, I found an issue with next@13.1.1 and mantine@5.10.0. 

It has major layout shifts when loading the page:

Here a example: (_the shown example is in production build_)
![layout_shift](https://user-images.githubusercontent.com/42061677/215285003-3d8321bc-b3f3-43cc-b9fe-9a71c44b8e96.gif)

Also from lighthouse report, it is taking more than 400ms to update the layout and it is clearly visible:
![image](https://user-images.githubusercontent.com/42061677/215285220-d47087fd-bed6-4a3a-bd2f-5edcea9ce037.png)

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
- You can use mantine-next-template as reference. It uses the latest version of Next.js (13.1.6) and does not have any ssr issues.
- If the issue is only reproducible in 13.1.1, rollback to previous patch/minor version or update to the latest version.
- If you use app directory or other experimental features, then you need to figure out how to support them on your own, we do not provide any support for alpha/beta/experimental features
- If you use custom emotion cache follow documentation to setup ssr for it

**Comment by avkash1** [comment]
```import { Html, Head, Main, NextScript } from "next/document";
import { createGetInitialProps } from "@mantine/next";

function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

//  Document.getInitialProp = createGetInitialProps();
Document.getInitialProps = createGetInitialProps();

export default Document;
```
@rtivital Thank you for the help. Sorry, it was my mistake, I forgot "s" in getInitialProps inside `_document.js`.
