### ISSUE TITLE
Mysterious `dot` prop for `Indicator`

### ISSUE THREAD

**Issue by Derrreks** [mantinedev/mantine#3566]
### What package has an issue

@mantine/core

### Describe the bug

In the `Indicator` component, the prop `showZero` does not correctly respond to `false` unless `dot={false}` is also provided.

In the docs ([here](https://mantine.dev/core/indicator/?t=props)), there is no description provided of what `dot` is or how to use it. However, even in the example for how to use `showZero` we can see that `dot={false}` had to be provided there.

Can we either remove this parameter if there is no other use for it (I'm happy to contribute this PR) or add a description/example for how to use it and/or why it is needed to be specified with `showZero`?

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Remove the `dot` prop from `Indicator`.

**Comment by rtivital** [comment]
I have no idea how it works, you are welcome to submit a PR with a fix to `v6` branch

**Comment by cyantree** [comment]
`dot` seems to be required because if `label={null}` nothing would be displayed:
```js
dot || (label != null &&
```
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Indicator/Indicator.tsx#L118

Also `dot` is missing from the hook dependencies.

But maybe the whole special number handling is too much for the component and showing/hiding the dot depending on the label should be the users responsibility:
```jsx
<Indicator label={count} dot={count > 0} inline size={16}>
```
In this case `showZero` would be obsolete and the condition would get a lot simpler:
```ts
  const isShowIndicator = useMemo(
    () => !disabled && dot,
    [disabled, dot]
  );
```

This would be a breaking change.

**Comment by maradney** [comment]
> the whole special number handling is too much for the component and showing/hiding the dot depending on the label should be the users responsibility

@cyantree I agree with this.
I would also change `dot` to be `showDot` or something

**Comment by cyantree** [comment]
I've missed `overflowCount` which is also a number based behaviour.

So in case we would remove this special handling `overflowCount` would be removed too.

However it would be possible to reintroduce this as a utility method that will be used via object spread:
```tsx
<Indicator {...someIndicatorNumberUtility(12, {overflowCount: 100, hideZeroOrBelow: true})} />
```

> I would also change `dot` to be `showDot` or something

Good point. `showDot` would be consistent to `showZero`.
Other components frequently use `with...` (as in `withCloseButton`, `withArrow`)
https://mantine.dev/core/dialog/?t=props
https://mantine.dev/core/modal/?t=props

However IMHO `with...` is meant for auxiliary elements whereas the dot is the main mechanic of the component.

Looking at `Modal`, it uses `opened` to control the main status. So another option would be `visible` instead of `dot`/`showDot`.
This would also remove the relation to the shape "dot". If you use another border radius it's more a square than a dot.

Sorry if this is too much splitting hairs over namings.

**Comment by maradney** [comment]
@cyantree I'm pro `visible` and `showDot` or even `hideDot`? 🤔 
Will you submit a PR? it seems you've done most of the work only the naming remains which could be decided quickly on discord 👍

**Comment by cyantree** [comment]
Yes, I can do that.
But first I want @rtivital's take on this.
- Should we remove number specific handling from `Indicator`?
- Should we instead introduce a functional helper that provides the appropriate props?
- Do you have any hints regarding renaming of the `dot` property?

**Comment by rtivital** [comment]
> Should we remove number specific handling from Indicator?

If we can keep current behavior, then yes

> Should we instead introduce a functional helper that provides the appropriate props?

No

> Do you have any hints regarding renaming of the dot property?

Not really. I'm not very knowledgeable about this logic – it was contributed by someone else. If you can remove it entirely, it would be great.

**Comment by cyantree** [comment]
Thanks for your feedback.

I think removing the `dot` property completely would make the conditional displaying a bit ugly. Because it's a wrapping component you would have to manage the whole block. E. g.

```jsx
{
  count > 0
    ? <Indicator label={count}><Avatar /></Indicator>
    : <Avatar />
}
```

So I would vote for a `visible` property that is optional and `true` by default. `LoadingOverlay` also uses a `visible` property. There it's required however because `LoadingOverlay` is expected to be a temporarily displayed component, that's ok. But because the `Indicator` might be used permanently I would consider the prop `optional`.

> Should we remove number specific handling from Indicator?
> > If we can keep current behavior, then yes

Yes, I think so:
`showZero={false}` would become:
```jsx
<Indicator visible={count > 0} label={count} />
```

`overflowCount={10}` would become:
```jsx
<Indicator label={count > 10 ? '10+' : count} />
```

So if this is fine for everybody I'll create a PR for this. @rtivital @maradny @Derrreks

**Comment by rtivital** [comment]
> Because it's a wrapping component you would have to manage the whole block. E. g.

There is `disabled` prop to remove indicator

I do not really like visible prop because it is planned to be used as a style prop in future

**Comment by cyantree** [comment]
IMHO `disabled` is a better fit for interactivity e. g. as in disabled input fields. So I think some wording with regarding to visibility would be better like `show` or `display`.

What will the `visible` prop do and how will it differ from this usecase? If it still amounts to showing/hiding the component maybe it's still ok to use the name and only swap the implementation details when ready?
Otherwise it might beconfusing to have two props with similar names and similar functionality.

**Comment by rtivital** [comment]
visible/hidden props will show/hide element at certain breakpoint

**Comment by rtivital** [comment]
Variant 1 is better

**Comment by cyantree** [comment]
Ok, thanks. I'll create a PR for it.
