### ISSUE TITLE
Mantine Form Validation and HMR does not work when used inside a managed modal.

### ISSUE THREAD

**Issue by arvind0598** [mantinedev/mantine#3569]
### What package has an issue

@mantine/modals

### Describe the bug

I've noticed two issues when using `useForm` and passing the form to a managed modal.
1. The select components do not show data when selecting an option.
2. `form.validate` and `form.isValid()` return false, but no errors are populated.

Both of these are fixed when the modal is closed and re-opened. 

These are not issues I face when using a regular modal from the core package.

This issue can be replicated on a sandbox too. 

### Note:
Probably related is also the fact that any changes I do in my code for the managed modal are not immediately reflected either, despite other changes correctly reflecting in my NextJS dev environment. This includes changes like the title and the labels of the confirm modal.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/flamboyant-pine-8nmmnn

### Instructions for Sandbox:
1. Open the regular modal, click on validate - should make the select box red and correctly raise an error.
2. Select an option, the error goes away and the selected option is visible.
3. Reload the page, open the managed modal. Click on validate, the message underneath shows `isValid` returns false.
4. Note that the select box does not turn red or raise any errors.
5. Close and reopen the managed modal - the error is now visible.
6. Select an option, the error message stays, but the selected option is not visible.
7. Close and reopen the managed modal - the option is now visible and the error message is gone.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
**`@mantine/modals` does not update modal that when state changes, what should I do?**
Example of code that does not work – https://codesandbox.io/s/loving-archimedes-2is4rx?file=/src/App.tsx

**Explanation**: When modal is opened with one the `@mantine/modals` function, child components cannot receive updated props. To fix that, create a separate component that will handle the state internally. Example – https://codesandbox.io/s/relaxed-euler-ipo3eu?file=/src/App.tsx

**But why?** When modal is opened, it is saved into state, in order to update the content, the function that was used to open it needs to be called again.
