### ISSUE TITLE
inputWrapperOrder prop of TimeInput Component console error: Warning: React does not recognize the `inputWrapperOrder` prop on a DOM element.

### ISSUE THREAD

**Issue by sakirsensoy** [mantinedev/mantine#3589]
### What package has an issue

@mantine/dates

### Describe the bug

inputWrapperOrder prop of TimeInput Component console error: Warning: React does not recognize the `inputWrapperOrder` prop on a DOM element.

### What version of @mantine/hooks page do you have in package.json?

v5.10.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
Here is an example for the problem:
https://codesandbox.io/s/lucid-gould-4e6o5p?file=/src/App.tsx

This issue is two-fold:
1. `inputWrapperOrder` is no valid property on `TimeInput` because the implementation doesn't interpret it that way. So that's an error in the types.
2. The correct place would be `wrapperProps={{inputWrapperOrder: []}}`. However `wrapperProps` doesn't have nice typings but a simple `Record<string, any>`.

This handling is used in many components. For example with `PasswordInput` its possible to use both variants without any problems.

However I find the implementation a bit risky:
1. At first various involved prop types get merged: https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/TimeInput/TimeInput.tsx#L29
2. Secondly various props get extracted and the rest goes to `others`: https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/TimeInput/TimeInput.tsx#L150
3. After extracting some styles the remaining props will be stored in `rest`: https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/TimeInput/TimeInput.tsx#L157
4. This `rest` gets spreaded to the `input` component: https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/TimeInput/TimeInput.tsx#L295

IMHO this is risky because it expects:
1. that all non-input props get extracted beforehand, otherwise unknown props would be rendered to the DOM as attribute (as seen in this issue)
2. that all merged prop types (step 1) get passed to the appropriate components. Otherwise they simply would get ommited.

So if e. g. a new prop gets introduced in `InputWrapper` it would immediately be accessible to all input components. However because of these two conclusions it would be rendered to the DOM and also not being passed to the `InputWrapper` component before being handled explicitly in the component.

- A solution might be avoiding these type merges and only allow input wrapper configuration via `inputWrapper={}`.
- Another solution might be flipping prop extraction where at first only the component props will be extracted and afterwards the rest will be passed to `InputWrapper`.

However if tackling the whole thing is too much (I think it might take some time to find a good solution and adjust all components) the simple fix would be extracting and passing `inputWrapperOrder` in `TimeInput` as done in `PasswordInput`: https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/PasswordInput/PasswordInput.tsx#L103

**Comment by cyantree** [comment]
#3520 contains the simple fix for this issue.

**Comment by rtivital** [comment]
Fixed in 5.10.15
