### ISSUE TITLE
Floating tooltip bug with dynamic disabled property

### ISSUE THREAD

**Issue by medihack** [mantinedev/mantine#3605]
### What package has an issue

@mantine/core

### Describe the bug

`Tooltip.Floating` stops working correctly (doesn't float anymore) when the `disabled` property is switched dynamically. The below sandbox demonstrates the problem. Simply hover over the boxes for some time from left to right and back again.

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/issue-mantine-tooltip-floating-d04508

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
The main culprit seems to be this line:
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Tooltip/TooltipFloating/use-floating-tooltip.ts#L78

There the dependency must be `refs.floating.current` instead of `refs.floating`.

After changing this the tooltip immediately picks up again when leaving the "dead zone".
However a quick flickering remains on reenabling as the tooltip at first is displayed at the point where it got disabled and only a bit later moves to the current mouse position.

What to do about it?

a) Somehow delay displaying one frame?
b) Move the tooltip also when it's disabled?

**Comment by rtivital** [comment]
If this is possible, the tooltip should be moved even when it is disabled
