### ISSUE TITLE
Controlled MultiSelect not working properly with openModal

### ISSUE THREAD

**Issue by farzindev** [mantinedev/mantine#3777]
### What package has an issue

@mantine/core

### Describe the bug

Components doesn't work the same way when we are using them inside modals using `openModal`. it's like the state is changing but UI is not changinge or something. I provided the codesandbox. thanks for the review.

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-openmodal-riofnk?file=/src/App.jsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
From FAQ:

**`@mantine/modals` does not update modal that when state changes, what should I do?**
Example of code that does not work – https://codesandbox.io/s/loving-archimedes-2is4rx?file=/src/App.tsx

**Explanation**: When modal is opened with one the `@mantine/modals` function, child components cannot receive updated props. To fix that, create a separate component that will handle the state internally. Example – https://codesandbox.io/s/relaxed-euler-ipo3eu?file=/src/App.tsx

**But why?** When modal is opened, it is saved into state, in order to update the content, the function that was used to open it needs to be called again.
