### ISSUE TITLE
Delay in loading CSS after upgrading to MantineUI version 6.0

### ISSUE THREAD

**Issue by ecatugy** [mantinedev/mantine#3922]
### What package has an issue

@mantine/core

### Describe the bug

I wanted to report a bug that I have encountered after upgrading to version 6.0 of MantineUI. When I run the 'yarn dev' command, there is a noticeable delay in loading the CSS, which causes a flash on the screen. This issue is affecting the user experience on my website, and I would appreciate it if you could look into it.

Do you have any idea when this bug might be fixed? I'm looking forward to hearing from you soon.

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
What framework do you use?

**Comment by ecatugy** [comment]
> What framework do you use?

The framework that I use is NextJS.

**Comment by toyi** [comment]
Just my two cents, but I just had this css loading delay issue.

I use NextJS too and everything was working fine yesterday, what I did this morning involved minor updates and the installation of `@mantine/notifications`.

Then, I don't know when exactly, I started experiencing these issues. After some diggings, I noticed that toying with `npm install` / `npm update` made the thing working / not working again.

What I noticed is that `@mantine/next` ,  `@mantine/ssr` and  `@mantine/styles` were still installed (lock file) in `6.0.4` wherehas `@mantine/core` was already `6.0.5` (which has been released this morning). Why ? Probably because I installed `@mantine/notifications`, I don't know exactly.

At the end, a `npm update` solved it (and all mantine dependencies are now `6.0.5`).

That's just some observations, maybe the problem is totally unrelated.

**Comment by ecatugy** [comment]
> Just my two cents, but I just had this css loading delay issue.
> 
> I use NextJS too and everything was working fine yesterday, what I did this morning involved minor updates and the installation of `@mantine/notifications`.
> 
> Then, I don't know when exactly, I started experiencing these issues. After some diggings, I noticed that toying with `npm install` / `npm update` made the thing working / not working again.
> 
> What I noticed is that `@mantine/next` , `@mantine/ssr` and `@mantine/styles` were still installed (lock file) in `6.0.4` wherehas `@mantine/core` was already `6.0.5` (which has been released this morning). Why ? Probably because I installed `@mantine/notifications`, I don't know exactly.
> 
> At the end, a `npm update` solved it (and all mantine dependencies are now `6.0.5`).
> 
> That's just some observations, maybe the problem is totally unrelated.

Thank you for the information. I followed your instructions and updated all mantine dependencies to version 6.0.5 using npm update. After the update, the css loading delay issue was resolved and everything seems to be working fine now.

I appreciate your input and the observations you made during the troubleshooting process. Your insights helped me to better understand the problem and find a solution more efficiently.

Thanks again for your help!
