### ISSUE TITLE
useForm reset type change

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#3956]
### What package has an issue

@mantine/form

### Describe the bug

I noticed when upgrading mantine form to the latest version that the `form.reset` type is different and requires an arrow function in the `onClick` handler to work properly. While this isn't a huge change, I would expect to be able to do:

```
<Button onClick={form.reset}></Button>
```

when not passing in any arguments (now that `form.reset` allows partial values)

However, this shows the following error:

> Type 'Reset<{ name: string; }>' is not assignable to type 'MouseEventHandler<HTMLButtonElement>'.
  Types of parameters 'values' and 'event' are incompatible.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/damp-cloud-ygrrc8?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by cyantree** [comment]
Hmm, the new behaviour was introduced in `6.0.5`.
I don't know if it shoud be considered a breaking change given that scenarios as yours now break because of it.

Because it's now accepting an argument the event argument passed by `onClick()` won't match the argument of `reset()` which (rightfully) triggers the error. So if it isn't considered a breaking change in mantine I'm afraid you have to use the more verbose form of `onClick={() => form.reset()}`.

If it is considered a breaking change the argument needs to be rolled back and maybe reintroduced as a separate method.

**Comment by rtivital** [comment]
I'll roll it back in next release

**Comment by rtivital** [comment]
Fixed in 6.0.6
