### ISSUE TITLE
NumberInput with useForm not handling onBlur properly

### ISSUE THREAD

**Issue by telmen** [mantinedev/mantine#3979]
### What package has an issue

@mantine/core

### Describe the bug

`<NumberInput />` not validating the first time when `validateInputOnBlur` is true. But it works the second time. Check the CSB.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/sweet-shape-93pb1q?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by cyantree** [comment]
It's probably related to my changes. I'll check it out. Thanks for the report.

**Comment by cyantree** [comment]
`NumberInput` propagates the new value on blur and also triggers `onBlur()` in the same rendering. However `useForm()` seems to expect value changes and `onBlur()` to happen in different renderings. Therefore the validation still uses the old values.

**Comment by cyantree** [comment]
Yes, I'm just thinking about a good solution.

**Comment by cyantree** [comment]
I'm currently finalizing the fix. After creating the PR I can provide a temporary package version for testing purposes.

I'm reworking the data flow handling to get it back in line with other components. That means it should trigger `onChange()` as soon as its value changes (and not holding this back until the component gets blurred).
But this wasn't the issue. The issue was that `onChange()` and `onBlur()` got triggered in the same run which didn't work well with scenarios that weren't designed for this.

So this will help with your issue and also with #3982.
FYI: That's "Aspect 2" in my [comment](https://github.com/mantinedev/mantine/pull/3756#issuecomment-1472172328).

**Comment by cyantree** [comment]
Please see the following example that uses the patched version introduced in #3984:
https://codesandbox.io/s/thirsty-chihiro-whhl7y?file=/package.json
