### ISSUE TITLE
Notification onClose doesn't fire if closed via hideNotification

### ISSUE THREAD

**Issue by cstrat** [mantinedev/mantine#41]
See demo here:
https://codesandbox.io/s/mantine-notification-onclose-notfiring-cn8ci?file=/src/App.js

When  useing `hideNotification` the `onClose` hook doesn't fire.

You can close the notification by clicking the `x` and see the alert.
If you close via the button - it doesn't work.

**Comment by rtivital** [comment]
Good catch, this is because this logic is handled in [NotificationContainer](https://github.com/mantinedev/mantine/blob/master/src/mantine-notifications/src/NotificationContainer/NotificationContainer.tsx), this logic should be moved on [NotificationsProvider](https://github.com/mantinedev/mantine/blob/master/src/mantine-notifications/src/NotificationsProvider/NotificationsProvider.tsx)

**Comment by rtivital** [comment]
[Released in 1.0.4](https://github.com/mantinedev/mantine/releases/tag/1.0.4)
