### ISSUE TITLE
Mantine DateTimePicker auto-tabbing and tabbing issues in Safari

### ISSUE THREAD

**Issue by jwenger100** [mantinedev/mantine#4172]
### What package has an issue

@mantine/dates

### Describe the bug

The fields do not auto tab to each other on Safari (for example, if I type 10 into the hour slot, it doesn't automatically move me over to minutes) Also, if I try to tab from the minutes to the check mark, it tabs to the address bar. It does seem to work properly in Edge and Chrome. It happens on the mantine.dev web page if you try out the control

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/dates/date-time-picker/

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
> The fields do not auto tab to each other on Safari

TimeInput component used in DateTimePicker is native `input[type="time"]` – there is no extra logic added to it. Not really sure whether this issue is fixable on library level. 

> Also, if I try to tab from the minutes to the check mark, it tabs to the address bar.

Most likely, this happens because Safari does not include `button` (and also `a`) tag in tab order by default – you need to enable this in Safari settings. See https://stackoverflow.com/questions/67901731/cannot-focus-button-using-tab-key-navigation-on-safari
