### ISSUE TITLE
Mantine core and form 6.0.10 select and multi select not working on safari 14.0.3 but do work on chrome

### ISSUE THREAD

**Issue by henriwoodcock** [mantinedev/mantine#4186]
### What package has an issue

@mantine/core

### Describe the bug

On safari I cannot do a select or multi select as no data is displayed when clicked. On chrome the values in `data` prop of `Select` or `Multiselect` work as expected

### What version of @mantine/hooks page do you have in package.json?

"@mantine/hooks": "^6.0.5"

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/brave-leakey-6ezd02?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I thought it's maybe hidden but after seeing it working on chrome I was even more lost

**Comment by rtivital** [comment]
I cannot reproduce this issue in Safari 16.2, I'd assume that is it an issue with Safari itself

**Comment by lgaspari** [comment]
Hey @henriwoodcock, are you sure the data is not displayed?

Something that seems different from 5.x to 6.x is that the `MultiSelect`'s dropdown is shown within `Modal`'s boundaries instead over it. Here's a comparison:

| 5.x | 6.x |
| :-: | :-: |
| ![image](https://user-images.githubusercontent.com/20128985/236290534-6134aa22-3db9-4247-b18b-37e44604cc7d.png) | ![image](https://user-images.githubusercontent.com/20128985/236290251-b1aee405-a393-457a-94a3-0989d225ff59.png) |

As you can see, I added `style={{ height: '600px' }}` to the `<form>` tag in the right picture just to denote that the data is actually visible, but due to having a small Modal, you're not seeing all of it just a couple of pixels.

Let me know your thoughts :)

PS: I'm using Safari 16.4

**Comment by isriram** [comment]
> Hey @henriwoodcock, are you sure the data is not displayed?
> 
> Something that seems different from 5.x to 6.x is that the `MultiSelect`'s dropdown is shown within `Modal`'s boundaries instead over it. 

Is there a way to override this function and show the dropdown over everything rather than inside `Modal` or `Card` in my case?

**Comment by isriram** [comment]
*sigh* Never mind. I used the withinPortal = true, and it now renders dropdown outside the card. I'd been searching for a solution for this for weeks.

**Comment by combo-2nd** [comment]
@isriram you save my time. big thanks
