### ISSUE TITLE
Spotlight is very sluggish with many actions (5000)

### ISSUE THREAD

**Issue by thomasserio** [mantinedev/mantine#4456]
### What package has an issue

@mantine/spotlight

### Describe the bug

I need to create a spotlight or autocomplete with thousands of items (about 5000), and performance is very sluggish when typing in the text field. I also tried the Autocomplete component and get similar performance.

I know that react-select has similar issues that can be worked around using react-window (see https://codesandbox.io/s/lxv7omv65l?file=/index.js). Could something like that be used here, where spotlight exposes the inner components via a prop similar to actionsWrapperComponent? Or maybe have the component use react-window internally?

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/thirsty-babycat-fczshl?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
`Autocomplete` doesn't have this problem if you cache `data` instead of recreating it on every render:
https://codesandbox.io/s/tender-colden-n59npx

`Spotlight` seems to take quite a bit of time in `useActionsState()` which results in a lag of about 600ms for your example on my machine.

`react-window` or something like that isn't needed here as both components only render a small amount of items.

**Comment by thomasserio** [comment]
Thanks for the Autocomplete example. I like this approach (and the PR you submitted).
