### ISSUE TITLE
NumberInput onChange type does not match useInputState

### ISSUE THREAD

**Issue by P1Rh0** [mantinedev/mantine#4774]
### What package has an issue

@mantine/hooks

### Describe the bug

The docs suggest you can use `const [value, setValue] = useInputState(0);` with NumberInput. However the onChange type does not match.
NumberInput:onChange - (value: number | ''): void
useInputState:setValue - (value: null | undefined | number | React.ChangeEvent<any>) => void

### What version of @mantine/hooks page do you have in package.json?

6.0.20

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I assume we need to change one of these types to align with the other but don't have enough domain knowledge to make that decision...

**Comment by P1Rh0** [comment]
Should NumberInput treat an empty string input as 0 perhaps and not have it in the onChange?

**Comment by rtivital** [comment]
Empty string is required to handle empty input field, it is different from 0. If you want to change value type of use-input-state, set type: `useInputState<number | ''>('');`

**Comment by morozovamv** [comment]
> Empty string is required to handle empty input field, it is different from 0. If you want to change value type of use-input-state, set type: `useInputState<number | ''>('');`

@rtivital Could you please mention it in the docs for the NumberInput? I also got confused because in the docs I see that useInputState should work with all mantine inputs, but it turns out that the type should be provided. Another confusing thing is that the type is number | string, now I see that the string is for empty state, but is wasn't clear since the beginning, a small note about it would help a lot. At first I thought that maybe I needed to deal with some corner cases, but I couldn't think of anything. Thank you in advance!
