### ISSUE TITLE
Unable to add icon to button

### ISSUE THREAD

**Issue by henrylin03** [mantinedev/mantine#4799]
### What package has an issue

@mantine/core

### Describe the bug

I am trying to add an icon to the left side of the text showing on my `<Button />` but it is not showing. 

I have followed the documentation on this: https://mantine.dev/core/button#left-and-right-sections, including testing other icons but it is still not showing. 

When I inspect elements, the `leftSection` attribute is as follows:
![image](https://github.com/mantinedev/mantine/assets/83106787/bfce5905-8bbb-4d30-ad06-fbaa037308da)
I'm unsure if this is the expected behaviour.

My code is in the Sandbox. 

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/leftsection-icon-not-showing-on-button-gzqt7d?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by mateuscqueiros** [comment]
Hello! I noticed your mantine packages in the sandbox are in 6.0.19 instead of 7.0.0. In 6.0, you need to use `leftIcon` to put an icon in left section, but in 7.0 it's `leftSection`. That could be your problem.

Also you are using justify on the Button component, but that is a prop of Group. 

Here's an example in 6.0 with the icon showing on the left:
[https://codesandbox.io/s/leftsection-icon-not-showing-on-button-forked-hhccwf?file=/src/App.tsx](https://codesandbox.io/s/leftsection-icon-not-showing-on-button-forked-hhccwf?file=/src/App.tsx
)
