### ISSUE TITLE
Wrong type resolution for `classNames` (at least)

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4853]
### What package has an issue

@mantine/core

### Describe the bug

Hi. I in process of refactor the whole codebase to mantine v7

I found another issue with types

See repro

Maybe this is related with all types of classNames, maybe only for tabs.

Currently the only workaround for similar cases is to include by myself classNames prop with copy-pasted resolved type
like `Partial<Record<TabsStylesNames, string>>`

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/keen-jerry-7lxqjg?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The type error is correct: `classNames` prop can accept either an object or a function. In your example, the function that can be passed to  `classNames` does not contain `root` property. Your fix for the issue is correct – you can narrow down the type on your side if you do not need to use a function. The same logic is applied to `styles` prop as well.

Example of using function with `classNames` prop – https://mantine.dev/styles/styles-api/#styles-api-based-on-component-props

**Comment by rtivital** [comment]
I cannot think of any other alternatives that have less boilerplate. If you need a type helper, you can use `StylesRecord` type:

```tsx
import { StylesRecord, ButtonStylesNames } from '@mantine/core';

type ButtonClassNames = StylesRecord<ButtonStylesNames, string>;
```
