### ISSUE TITLE
NextJS Integration Page Should Mention `optimizePackageImports`

### ISSUE THREAD

**Issue by TClark1011** [mantinedev/mantine#5068]
### Link to the page where something nasty is located

https://mantine.dev/guides/next/

### Exact quote of what is wrong

I think it would be helpful if the page could include instructions for adding mantine packages into the NextJS config `optimizePackageImports`, as the nextjs template does: https://github.com/mantinedev/next-app-template/blob/master/next.config.js .

This is important for people who want may use an alternative project template (eg; `create-t3-app`) and are using mantine.

Apologies if this is not the correct place for this feedback.

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment]
- This is an experimental Next.js feature that may be changed or removed in future
- The application works correctly without this feature enabled
- If the user experiences any problems, the issue is pinned and the reference is available is corresponding template

I do not see a reason to add and maintain this on the documentation website
