### ISSUE TITLE
When clearing a NumberInput and then adding back a number, zodResolver reports error

### ISSUE THREAD

**Issue by MartinMuzatko** [mantinedev/mantine#5218]
### What package has an issue?

@mantine/form

### Describe the bug

I'm then unable to resolve the error and always get "Expected number, received string"

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.0

### If possible, please include a link to a codesandbox with a minimal reproduction

codesandbox.io/s/adoring-newton-pt79dw?file=/src/Demo.tsx

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

Yes

**Comment by 7iomka** [comment]
I think this is realted with how now value is exposed.
For some reason, when NumberInput first time receive a string value (when it is empty), after we see that typeof value is string.
https://codesandbox.io/s/ecstatic-haslett-jczdsw?file=/src/App.tsx
This is related how internally mantine handle onChange value with vendor
So we need to find a solution somehow
![telegram-cloud-photo-size-2-5334748595003446414-y](https://github.com/mantinedev/mantine/assets/18473137/7422a1f9-c18e-4c75-af8a-0c7339de6885)
 
@rtivital said he'd see what he could do about it, because so far it's creating a number of complications with validation services and in callbacks.

**Comment by rtivital** [comment]
Fixed in [7.2.2](https://github.com/mantinedev/mantine/releases/tag/7.2.2)

**Comment by premier213** [comment]
![image](https://github.com/mantinedev/mantine/assets/4321174/4c406e3e-c707-4f83-b6da-981a84f96708)

![image](https://github.com/mantinedev/mantine/assets/4321174/7959110b-8d2a-4d1a-941c-351421d354be)

![image](https://github.com/mantinedev/mantine/assets/4321174/d7b815fa-57b9-49cd-8c59-6e7a5638140b)

i used zod with v7.51
