### ISSUE TITLE
Make @mantine/tiptap not dependent on tabler-icons

### ISSUE THREAD

**Issue by bvkimball** [mantinedev/mantine#5279]
### What package has an issue?

@mantine/tiptap

### Describe the bug

I use lucide-react, tabler-icons are great just not what i use.
but now i have to bundle them as dependency.

Not sure how you make it optional.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rasyidf** [comment]
I agree with this.
Building my project with  mantine/tiptap and Vite significantly slows down, especially on my low-performance laptop. The delay is substantial, around 20 seconds on vercel and minutes on my less capable machine. The problem seems to be the transformation of 4000 icons, even though only 26 of them are utilized by tiptap.

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
