### ISSUE TITLE
False error: MantineProvider was not found in component tree, make sure you have it in your app

### ISSUE THREAD

**Issue by simonszalai** [mantinedev/mantine#5306]
### What package has an issue?

@mantine/notifications

### Describe the bug

I'm getting this error:

```
Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app
    at useMantineTheme [...]
```

As opposed to what the error says, I actually have MantineProvider in my app:

```
        <MantineProvider theme={theme} defaultColorScheme="light" cssVariablesResolver={cssVarResolver}>
          <Notifications />
          [...]
        </MantineProvider>
```

The error triggers only if I use the Notification component.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
Please provide a sandbox with a reproduction. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

**Comment by mlshvdv** [comment]
The same for @mantine/carousel using nextjs

**Comment by kentare** [comment]
I have the same issue suddenly appear in my repo. I tried to reproduce the issue in codesandbox, but wasn't able so I looked at what I did that might have broken the 

I use a pnpm monorepo and introduced a new app that uses mantine. When I remove the new app, everything worked as expected. So I think it is something with the external dependency resolving. Will look further into it tomorrow.

**Comment by kentare** [comment]
Update: Turned out it was a local caching issue. I deleted node_modules and the .next folder before I ran the install and build process. Now everything works as expected.

**Comment by mlshvdv** [comment]
For everyone who meet this problem:

in my next.config.js the `experimental` property was added like that:
```js
experimental: {
        optimizePackageImports: [
            '@mantine/core',
            '@mantine/hooks'
        ],
}
 ```

I've deleted it and now it works!

**Comment by adamdrake210** [comment]
I also get this issue and I also am working in a pnpm monorepo. This happened when upgrading from v6 to v7.2.2. If I remove the <Notifications /> component from the app then everything loads fine.

I am using vite-react (not Nextjs). 

```
export default function AppProviders({ children }: AppProviderProps) {
  const queryClient = new QueryClient();

  return (
    <MantineProvider theme={{ ...theme }} defaultColorScheme="light">
      <Notifications />
      <QueryClientProvider client={queryClient}>
        {children}
        <ReactQueryDevtools initialIsOpen={false} />
      </QueryClientProvider>
    </MantineProvider>
  );
}

```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)
7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction
No codesandbox as would require setting up a monorepo

Do you know how to fix the issue
No

Do you want to send a pull request with a fix?
No

**Comment by rtivital** [comment]
The issue is not related to `@mantine/*` packages – they work as intended. If you think that the error is with dependencies resolution, you can open an issue in your package manager repository.

**Comment by nkhi** [comment]
@rtivital There is no other forum to discuss these issues, which are indeed related to how `@mantine/*` packages work with other standard libraries like Next.JS. Please encourage discussion and threads in these GitHub issues for the sake of the community 🙇🏻. Perhaps this can be tagged with "Discussion" if you're concerned about the # of open tickets. 

I'm still encountering this issue with the dependency versions below. I am trying to render a <Dropzone /> inside of a <Modal /> (which is natively rendered as a <Portal />), so I'm assuming there is something wrong with the component hierarchy when Portals are involved. My only other thought is maybe I need to update the version of Dropzone to 7.3.1.

```
dependencies:
@mantine/core 7.3.1            @mantine/utils 6.0.21          postcss-preset-mantine 1.12.0  
@mantine/dates 7.3.1           @phosphor-icons/react 2.0.15   react 18.2.0                   
@mantine/dropzone 7.3.2        dayjs 1.11.10                  react-dom 18.2.0               
@mantine/hooks 7.3.1           next 14.0.3                    styled-components 6.1.1        
@mantine/notifications 7.3.1   next-auth 4.24.5               

devDependencies:
@types/node 20.10.0
@types/react 18.2.39
@types/react-dom 18.2.17
eslint 8.54.0
eslint-config-next 14.0.3
postcss-preset-env 9.3.0
typescript 5.3.2
```

**Comment by nkhi** [comment]
@rtivital There is no other forum to discuss these issues, which are indeed related to how `@mantine/*` packages work with other standard libraries like Next.JS. Please encourage discussion and threads in these GitHub issues for the sake of the community 🙇🏻. Perhaps this can be tagged with "Discussion" if you're concerned about the # of open tickets. 

I'm still encountering this issue with the dependency versions below. I am trying to render a <Dropzone /> inside of a <Modal /> (which is natively rendered as a <Portal />), so I'm assuming there is something wrong with the component hierarchy when Portals are involved. 

```
dependencies:
@mantine/utils 6.0.21           next-auth 4.24.5               
@mantine/core 7.3.2             @phosphor-icons/react 2.0.15     
@mantine/dates 7.3.2           react 18.2.0                   
@mantine/form 7.3.2             react-chartjs-2 5.2.0          
@mantine/hooks 7.3.2           react-dom 18.2.0               
@mantine/next 6.0.21           postcss-preset-mantine 1.12.2
@mantine/spotlight 7.3.2      next 14.0.3                    

devDependencies:
@types/node 20.10.5
@types/react 18.2.45
@types/react-dom 18.2.18
eslint 8.56.0
eslint-config-next 14.0.3
postcss-preset-env 9.3.0
typescript 5.3.3
```

**Comment by rtivital** [comment]
You are welcome to open a new issue if you can provide a minimal reproduction. Issues that cannot be reproduced are closed as incomplete.

**Comment by sohan-dutta** [comment]
I got it resolved by removing the `pnpm-lock.yaml` and running pnpm install again in my pnpm monorepo.

**Comment by simonszalai** [comment]
I have this issue with Remix on Mantine 7.4.1 (also on 7.2.2). I cleared node_modules and package-lock.json, but the error is still occuring.

**Comment by simonszalai** [comment]
Thanks @rtivital , but I found that article before and unfortunately none of those solve my issue. I think it could be some weird caching thing, because it used to work and at one point without apparent reason it broke. First I was getting this error only when I used Notifications, but now also with Modals. All mantine packages have the same version, tried deleting node_modules, package-lock.json and also cleared npm cache, none of those helped.

**Comment by ghana7989** [comment]
Issue exists still and none of the fixes work, facing issues with basic cypress setup

**Comment by leonschwanitz** [comment]
https://github.com/mantinedev/mantine/issues/5884

**Comment by jeanbenoit-richez** [comment]
There is so many people having the same bugs that it can't be just a "problem" on our side.
I check in my bundled lib folder and there is only one @mantine/core package existing.
I check in the app that using my lib and same behaviour.

**Comment by tawanaj** [comment]
Got this working for our team, turns out this was actually a peer deps issue. We have a front end monorepo with multiple apps and are in the process of adding an additional vite + react app using pnpm. 

We had multiple **@types/react** versions defined for different apps and packages. Mantine/core however, was pinned at the root and used as a peer dep everywhere. So if one app had a different @types/react version defined, it would create a duplicate @mantine/core with these additional deps in the lockfile as react/types is also a peer dep of mantine. 

_**Summary of problem:**_
Having mantine/core defined as a peer dep everywhere will cause different variations if all apps and packages are not aligned across the border with the peers of mantine/core (**_react, react-dom, @types/react(transitive)_**)

_**Fixed by:**_
1. Moving @types/react to the root package.json 
2. Made react/types a peer dep for all consuming apps and packages
3. Deleted the  pnpm-lockfile 
4. Re ran install and this removed the duplicate mantine/core flavors

Hope this helps someone from the days of spinning! 🙏

**Comment by jeanbenoit-richez** [comment]
> Got this working for our team, turns out this was actually a peer deps issue. We have a front end monorepo with multiple apps and are in the process of adding an additional vite + react app using pnpm.
> 
> We had multiple **@types/react** versions defined for different apps and packages. Mantine/core however, was pinned at the root and used as a peer dep everywhere. So if one app had a different @types/react version defined, it would create a duplicate @mantine/core with these additional deps in the lockfile as react/types is also a peer dep of mantine.
> 
> _**Summary of problem:**_ Having mantine/core defined as a peer dep everywhere will cause different variations if all apps and packages are not aligned across the border with the peers of mantine/core (**_react, react-dom, @types/react(transitive)_**)
> 
> _**Fixed by:**_
> 
> 1. Moving @types/react to the root package.json
> 2. Made @types/react a peer dep for all consuming apps and packages
> 3. Deleted the  pnpm-lockfile
> 4. Re ran install and this removed the duplicate mantine/core flavors
> 
> Hope this helps someone from the days of spinning! 🙏

Hi,
Thank you, it's helps ! I finally succeed to make it works 🙏🏻

**Comment by RabeeAbuBaker** [comment]
@rtivital  I'm still facing this issue, I have created a [repo](https://github.com/RabeeAbuBaker/mantine-provider-error-example) with minimal reproduction. 
The readme is explaining everything I suppose. 

<img width="1073" alt="image" src="https://github.com/mantinedev/mantine/assets/38038348/7cb0036f-8fa5-41bc-a50a-2a8501b53317">

Let me know if you have any questions. Hopefully it's something I messed up and can be easily solved!

**Comment by Taewa** [comment]
In my case, I wanted to set Mantine in Storybook and I was missing some steps from: https://mantine.dev/guides/storybook/

**Comment by RabeeAbuBaker** [comment]
> > You are welcome to open a new issue if you can provide a minimal reproduction. Issues that cannot be reproduced are closed as incomplete.
> 
> @rtivital I'm still facing this issue, I have created a [repo](https://github.com/RabeeAbuBaker/mantine-provider-error-example) with minimal reproduction. Should I open a new issue since this one is closed?
> 
> The readme is explaining everything... I suppose.
> 
> ![image](https://private-user-images.githubusercontent.com/38038348/315571939-989a1d3b-f2bf-4b83-a66b-9b5726889fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNDQ1MjUsIm5iZiI6MTcxMTE0NDIyNSwicGF0aCI6Ii8zODAzODM0OC8zMTU1NzE5MzktOTg5YTFkM2ItZjJiZi00YjgzLWE2NmItOWI1NzI2ODg5ZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDIxNTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTYyMmY0NmNjMDNjNTBkOGM2MzhmNzhmMDY5NTRjNDA4NDk4NjdmYjhjMDQ3YWI4ZTBlNmQ3OTBjZjU0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFKq8IKH-a2YVpsTCeYN2E33W3YCtUWOIctYfwFGzpE)
> 
> Let me know if you have any questions. Hopefully it's something I messed up and can be easily solved!

An update about this... we were able to fix this by adding mantine as an [external](https://rollupjs.org/configuration-options/#external) dependency under vite's build options. 

Here's a PR within the repo that fixes the issue https://github.com/RabeeAbuBaker/mantine-provider-error-example/pull/1 (It's not the perfect PR and needs some clean up, but it will do for now. 

Hopefully this helps someone out there struggling with this... God knows the shenanigans I had to pull trying to solve this.

**Comment by tabledK** [comment]
It turns out happening again 

> In my case, I wanted to set Mantine in Storybook and I was missing some steps from: https://mantine.dev/guides/storybook/

It turns out happening again. Reinstalling packages & cleaning up the npm cache doesn't help :/

**Comment by Taewa** [comment]
It's solved. I did probably more than 10 times of `npm cache verify && npm install`.
Also version up  from `7.6.2` to `7.7.1`
But not sure if npm cache is the root-cause 🤔

**Comment by bitIO** [comment]
FWIW the error still exists with a new Next project using pages router. The error remains while using any of the plugins (Notifications, Modals, etc) and removing them from the `_app.tsx` file  renders the default page.

**Comment by hunterwilhelm** [comment]
I didn't see anyone with my solution yet for a monorepo. 

Change your package.json @mantine/ packages to point to the other folder's node_modules.

`package.json`
```json
    "@mantine/code-highlight": "file:../shared-folder-in-same-repo/node_modules/@mantine/code-highlight",
    "@mantine/core": "file:../shared-folder-in-same-repo/node_modules/@mantine/core",
    "@mantine/dates": "file:../shared-folder-in-same-repo/node_modules/@mantine/dates",
    "@mantine/dropzone": "file:../shared-folder-in-same-repo/node_modules/@mantine/dropzone",
    "@mantine/hooks": "file:../shared-folder-in-same-repo/node_modules/@mantine/hooks",
    "@mantine/modals": "file:../shared-folder-in-same-repo/node_modules/@mantine/modals",
    "@mantine/notifications": "file:../shared-folder-in-same-repo/node_modules/@mantine/notifications",
    "@mantine/tiptap": "file:../shared-folder-in-same-repo/node_modules/@mantine/tiptap",
```

As an added bonus it saves some disk space!

**Comment by ecatugy** [comment]
Same issue here. I’m using version 7.9 of Mantine, and I’ve tried all the above solutions but nothing works, even following what’s described at https://help.mantine.dev/q/mantine-provider-missing. In my case, the problem is with the package @mantine/carousel. This issue seems to be occurring for several people.

**Comment by arunkp** [comment]
We are constantly bothered with this problem since a month now, it is happening only on production for us and it is hard to traceback what is really going on with this issue. Anyone found any solution?

<img width="846" alt="Screenshot 2024-05-13 at 17 01 16" src="https://github.com/mantinedev/mantine/assets/4560500/5b4fa14a-7956-4679-9647-a8c85530633a">

**Comment by RabeeAbuBaker** [comment]
> We are constantly bothered with this problem since a month now, it is happening only on production for us and it is hard to traceback what is really going on with this issue. Anyone found any solution?
> 
> <img alt="Screenshot 2024-05-13 at 17 01 16" width="846" src="https://private-user-images.githubusercontent.com/4560500/330106732-5b4fa14a-7956-4679-9647-a8c85530633a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTY3MDQsIm5iZiI6MTcxNTYxNjQwNCwicGF0aCI6Ii80NTYwNTAwLzMzMDEwNjczMi01YjRmYTE0YS03OTU2LTQ2NzktOTY0Ny1hOGM4NTUzMDYzM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTYwNjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI2Y2VhYThmMTE3YTZkZTgyYmE4NTJlNjU2MGVmNWY5NTFkMWU0OGQ0YjdmN2I0NWJhOWJiYzFiNDc0MGEyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-55B57mn5h0sBiASqaHb-yJpvsyucaIi0D40nnWsnj8">

@arunkp Have you tried this? https://github.com/mantinedev/mantine/issues/5306#issuecomment-2015996434
Using `rollupOptions.external` was the only thing that fixed the issue for me.

**Comment by SimonHFrost** [comment]
Make sure you're using a consistent routing strategy. I was mixing app and page routing which caused the `MantineProvider was not found...` error.

I fixed it by moving `pages/signup.tsx` to `app/signup/page.tsx`. 

Hope this helps someone ❤️

**Comment by arunkp** [comment]
I found the issue when using the component Divider, removing this component helped us solve the problem with errors.

**Comment by apcjs** [comment]
I faced this problem when one of a custom package I wrote was set to common-js in my package.json. Had to change it to module and it started working fine

**Comment by SirBenedick** [comment]
I was facing the same problem after updating to 7.9.2.
After going through [mantine-provider-missing](https://help.mantine.dev/q/mantine-provider-missing), updating everything, deleting the node modules and reinstalling it still didn't work. 

So I check the versions inside the package-lock. For some reason every package updated except for the @mantine/dates package, which was stuck at 7.9.1. 

My fix:

1. delete all node_modules folders
2. delete package-lock.json
3. npm install

**Comment by philr35** [comment]
I ran into this same issue and clearing `node_modules` and `lock` file had no effect on my Astro project.

The core issue of the problem seemed to be from the structure of the code itself where I was trying to use `useMantineTheme` in the same component I was importing my MantineProvider component and that is why it complained, and why the error actually makes sense.

**This will not work:**
```
export const App: React.FC<Props> = (props) => {
    const theme = useMantineTheme();

    return (
        <MantineProvider>
            <ChildA color={theme.colors.blue[7]} />
        </MantineProvider>
    );
};

const ChildA = ({ color }) => {
 // Do stuff
}
```

**This _will_ work:**
```
export const App: React.FC<Props> = (props) => {
    return (
        <MantineProvider>
            <ChildA />
        </MantineProvider>
    );
};

const ChildA = () => {
  const theme = useMantineTheme();

 // Do stuff
}
```

This required some restructuring of my files and code logic, but I got it working once all calls to the Mantine API layer were nested **under** the parent component that imports the provided. Hope this helps

**Comment by tiwka19** [comment]
> I ran into this same issue and clearing `node_modules` and `lock` file had no effect on my Astro project.
> 
> The core issue of the problem seemed to be from the structure of the code itself where I was trying to use `useMantineTheme` in the same component I was importing my MantineProvider component and that is why it complained, and why the error actually makes sense.
> 
> **This will not work:**
> 
> ```
> export const App: React.FC<Props> = (props) => {
>     const theme = useMantineTheme();
> 
>     return (
>         <MantineProvider>
>             <ChildA color={theme.colors.blue[7]} />
>         </MantineProvider>
>     );
> };
> 
> const ChildA = ({ color }) => {
>  // Do stuff
> }
> ```
> 
> **This _will_ work:**
> 
> ```
> export const App: React.FC<Props> = (props) => {
>     return (
>         <MantineProvider>
>             <ChildA />
>         </MantineProvider>
>     );
> };
> 
> const ChildA = () => {
>   const theme = useMantineTheme();
> 
>  // Do stuff
> }
> ```
> 
> This required some restructuring of my files and code logic, but I got it working once all calls to the Mantine API layer were nested **under** the parent component that imports the provided. Hope this helps

mantine components works with astro? I thought it was impossible, because astro can't use context.

**Comment by evolfo** [comment]
I'm currently getting this error only when running `jest` tests, has anyone encountered this before? The app works fine aside from that.

**Comment by GitHunter0** [comment]
@rtivital , @achmurali , please can you reopen this issue? I'm receiving the same error message, which is breaking my app.

**Comment by jkhaui** [comment]
> mantine components works with astro? I thought it was impossible, because astro can't use context.

I remember reading this too - it's the [official stance of Mantine](https://help.mantine.dev/q/can-i-use-mantine-with-astro) - but it's also incorrect.

Mantine **does**, in fact, work with Astro. It just suffers from the same limitations which apply to any project using React Context with Astro. Specifically, using a context provider such as `<MantineProvider/>` _within_ a React island in Astro (i.e. within a `.tsx/.jsx` file) **will** work. But using `<MantineProvider/>` in a `.astro` file will **not** work.

Anyway, I'm here because yet another framework is struggling with the dreaded "MantineProvider was not found" error.

Waku is a new React meta-framework, built on Vite with first-class RSC support. I initially thought the problems outlined in [this issue](https://github.com/dai-shi/waku/issues/421) when integrating Mantine with Waku were on Waku's bundler side, but now I'm not so sure. A recent Waku release fixed some bugs regarding CJS/ESM dual-package hazard. Yet it seems like Mantine is still the anomaly exhibiting some really odd behaviour with its context provider.

**Namely - as others in this thread have also described - if you include `<MantineProvider/>` via a custom component (e.g. `my-providers.tsx` which imports MantineProvider), and use this custom component in the root layout, it results in the mantine provider not being detected. However, directly adding it to the root layout as an import from `@mantine/core` **does** work.**

This is really odd behaviour which I've never experienced before. It's especially strange because `<MantineProvider/>` is the only context provider which causes it. Creating a new React Context and importing it via a custom component doesn't result in this error. Also, it only happens in dev and not prod, which indicates that ESBuild is struggling with module resolution heuristics (this could be coming directly from Mantine, or possibly a 3rd-party dependency with badly configured ESM exports).

The fact that the same behaviour has been seen in both Next.js + webpack/turbopack setups, as well as Vite-based frameworks, to me is a clear indication that something deep within Mantine (or perhaps even one of its dependencies) is fundamentally misconfigured.

I love this library and appreciate from first-hand experience how difficult these issues can be to debug. But given the number of people experiencing difficulties, at the very least it should be openly acknowledged so that a proper resolution can be found more quickly.

**Comment by jkhaui** [comment]
Alright! I think I've finally uncovered the root cause of this issue and would like to propose a fix @rtivital. Thanks to everyone in this thread who shared their experience which helped narrow down the bug.

The fundamental problem is that `@mantine/core` has its peer dependency of react fixed to `18.2.0`. Additionally, all mantine packages are prebuilt to distribute cjs & esm versions when a user runs `npm i @mantine/core`  in their project.

It appears that when the aforementioned factors are then combined with a consuming application which uses a different react version (in the case of Waku, it relies on v`19.0.0-rc.0`), some strange behaviour is triggered where Mantine context will **briefly** return `null` & hence the "MantineProvider not found" error will be thrown according to this line: https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/core/MantineProvider/MantineThemeProvider/MantineThemeProvider.tsx

To verify that this is indeed what is happening, I pulled the mantine monorepo, changed the react version in `@mantine/core` to match the one in my project, and finally built mantine core (& mantine hooks) locally and consumed this build within my application. No more issues.

My next thought was to try and lock all versions of React in my project to the same version using "resolutions" in package.json along with the latest versions of Mantine. But this didn't work.

So finally, I tried a local Mantine build which still uses the fixed `18.2.0` versions of React while also modifying `useMantineTheme` from:

```
export function useMantineTheme() {
  const ctx = useContext(MantineThemeContext);
  if (!ctx) {
    throw new Error(
      '@mantine/core: MantineProvider was not found in component tree, make sure you have it in your app'
    );
  }

  return ctx;
}
```

to:

```
export function useMantineTheme() {
  return useContext(MantineThemeContext) || DEFAULT_THEME;
}
```

...and again, everything works perfectly now.

**Solution:**

The solution from here seems pretty obvious, just do any one of the following:

1. Remove the null check for ctx from `useMantineTheme` + add `DEFAULT_THEME` as a fallback
2. Doing 1) would make `useMantineTheme` identical to `useSafeMantineTheme`, so they might as well be combined into a single hook?
3. Or possibly even just replace the `null` initial value for `MantineThemeContext` to be `DEFAULT_THEME` instead.

I can open a PR with these changes.

What I don't understand is: what's the point in throwing an error if ctx is null, if React itself doesn't throw and is resilient enough to recover from this supposedly null value?

**Comment by rtivital** [comment]
> Remove the null check for ctx from useMantineTheme + add DEFAULT_THEME as a fallback

This will not work. In this case, you will only hide the problem. It is basically: “I do not like the error message, so we should just remove it instead of resolving the issue”.

> Or possibly even just replace the null initial value for MantineThemeContext to be DEFAULT_THEME instead.

Then instead of a clear error about missing MantineProvider you will get a hydration mismatch error. The theme is used to generate some HTML attributes and tags.

> What I don't understand is: what's the point in throwing an error if ctx is null, if React itself doesn't throw and is resilient enough to recover from this supposedly null value?

If `useMantineTheme` throws an error, it means that there is no MantineProvider in the component tree. MantineProvider has many functions that are not related to the context but still required to run the application. Without MantineProvider all styles of components will be broken.

**Comment by jkhaui** [comment]
> This will not work. In this case, you will only hide the problem. It is basically: “I do not like the error message, so we should just remove it instead of resolving the issue”.

Ok, perhaps I didn't explain my findings clearly. My apologies - let me state my understanding again:

As the title of this thread states, the issue that everyone here is facing is based on a "false error" and not an actual error which woud break the application at runtime.
In other words: we **definitely do have a mantine provider wrapping our application**, but under certain conditions (see my previous post) the null check inside `useMantineTheme` still gets triggered **despite the mantine context having already been created**. And this is what is causing everyone grief.

If it helps you to visualise this scenario, I replaced the ctx null check with a console.log statement logging the mantine theme, installed this local build in my app, and took a screenshot of the server + browser consoles after startup:

![image](https://github.com/mantinedev/mantine/assets/36477474/a373fabd-54b6-4c80-8b18-661caab2bf2b)

![image](https://github.com/mantinedev/mantine/assets/36477474/64f84c32-0363-48bb-9cfa-47818dfe7b19)

As you can see, at no point does the mantine theme (logged from within `useMantineTheme`) ever log a null value; neither on the server or browser.

Furthermore, there are no hydration errors (no error messages are seen at all, in fact) and the application functions exactly as expected.

Does this not demonstrate the following?
1. There are no actual errors or problems
2. For some reason the null check in `useMantineTheme` gets triggered even though `ctx` absolutely does exist. I have no idea why this would happen, but If I had to guess, I'd speculate that something about the way React handles async components in dev has changed in v19.

**Comment by rtivital** [comment]
I do not really understand where null is coming from. If the theme is present both on server and on client then in which case the context returns null? I'd rather fix the issue of null context rather than removing the error.

For the previous post: as far as I understand, it should not really matter what Mantine has in peer dependencies – these dependencies are fully supplied by the application, Mantine packages do not install their own version of react (18.2.0 is a recommendation, not an instruction to use specific version).

**Comment by jkhaui** [comment]
> I do not really understand where null is coming from. If the theme is present both on server and on client then in which case the context returns null? I'd rather fix the issue of null context rather than removing the error. 

Firstly - thank you very much for acknowledging the issue 🙏 

Yeah exactly, I have no idea how the value can ever be null either. All I can do is report my findings which looks like some weird edge-case is triggered when a library uses a different React version from the main app (observed by the error going away after I aligned the React & React DOM versions in Mantine with the version in my application)

> For the previous post: as far as I understand, it should not really matter what Mantine has in peer dependencies – these dependencies are fully supplied by the application, Mantine packages do not install their own version of react (18.2.0 is a recommendation, not an instruction to use specific version).

Yeah I was also under the same impression, but I think the default behaviour of npm has changed such that `npm i` will automatically install all peer dependencies as well now.

Let me try some things and report back

**Comment by jkhaui** [comment]
**Update:**

After spending countless hours on this, I would like to re-clarify my understanding:

**ISSUE**

In a development environment, npm will, **by default, install the peer dependencies of any direct dependency in a project's `package.json`.** E.g. In `my-app/package.json` with `@mantine/core` as a direct dependency, running `npm i` will also install react `^18.2.0` transitively because this is listed in mantine core's package.json.

This does **NOT** appear to happen in production builds.

The consequence of having multiple react versions in a dependency graph appears to be the triggering of a difficult-to-reproduce bug **where react will sometimes read the value of an existing context provider as null**.

It is the result of npm stealthily changing its handling of peer dependencies, without first broadly announcing this along with educating the community on the far-reaching implications of this change.

**EVIDENCE**

1. When installing the latest version of mantine directly from npm in a fresh project (with react v19-rc as a direct dependency in the project's package.json), this error is thrown:
![mantine-1](https://github.com/mantinedev/mantine/assets/36477474/23bf2960-e548-403b-9df2-2c2ba6c334cf)

While it can be bypassed using `--legacy-peer-deps`, all this does is allow dependencies to be installed but will not fix the "missing context provider" issue which is _fundamentally caused by multiple versions of react existing within a project._

2. Installing mantine as a local build, i.e. using an alias to point the version of `@mantine/core` and `@mantine/hooks` to a version of the libraries compiled locally, actually fixes the issue entirely - even if react ^18.2.0 is still listed as a peer dependency - **because npm suddenly changes its behaviour to override conflicting peer dependencies.**

^ This last sentence in bold is the final key which I didn't understand when I wrote my previous posts. It also holds the information we need for the solution (explained below)

![image](https://github.com/mantinedev/mantine/assets/36477474/fdfda95f-ebd4-4e4e-b92a-cfa598834dde)

![mantine-2](https://github.com/mantinedev/mantine/assets/36477474/d93ea8ed-e39c-46b3-9d26-e76c65ac1d7f)

**SOLUTION:**

**There must be a way for consumers of mantine packages to override its peer dependency of react ^18.2.0.**

It's crazy but I still cannot find a clear or recommended way to do this. Any input from others more knowledgeable on best practices for de-duping multiple library versions within a dependency graph would be much appreciated.

With react 19 on the horizon, let's fix this once-and-for-all as a community so no one else has to waste ridiculous amounts of time trying to understand what's going wrong.

**Comment by rtivital** [comment]
Can you please check if setting version to `>=18.2.0` will resolve the issue?

**Comment by rahadi23** [comment]
Hi, I know the issue is closed and sorry to add comment here, but I'm encountering this issue as well, especially when using NextJS. So I made the sandboxes to reproduce the issue. Please check this and hope this helps.

Steps I've taken to reproduce:

## Created a component lib package

This is what I wanted to achieve initially, i.e. to be able to make a package of shared component library for my other projects. I've made [a simple repo](https://github.com/rahadi23/mantine-5306) consisting of [a random Mantine UI component (StatsControls)](https://ui.mantine.dev/category/stats/#stats-controls) and built the package with Rollup.

Please feel free to also check the corresponding Rollup. Basically I've applied the [rollup-plugin-peer-deps-external](https://www.npmjs.com/package/rollup-plugin-peer-deps-external) to make sure that the package doesn't bundle Mantine on its own.

After the build finished, I used `npm pack` to create the package's `.tgz` file and therefore can be installed to the sandboxes with `yarn add package/mantine-5306-1.0.0.tgz` directly. The package then can be imported with `import { StatsControls } from 'mantine-5306'`.

## Attempt 1: Vite Sandbox

Please check [this sandbox](https://codesandbox.io/p/devbox/ui-lib-vite-68fnpm) that is based on https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx . Attempt to reproduce issue with this template is unsuccessful. Everything is working normally.

## Attempt 2: NextJS Sandbox

Meanwhile [this sandbox](https://codesandbox.io/p/devbox/ui-lib-next-cz9444) is based on [next-pages-min-template](https://github.com/mantinedev/next-pages-min-template). When `<StatsControls />` is added to `pages/index.tsx`, the issue occurred.

I'm not really sure what caused the problem though, therefore I'm currently can't propose any workaround yet 😅 . But I'm convinced that this is caused by RSC or NextJS in particular. Maybe further settings needs to be done with NextJS specifically?

**Comment by jkhaui** [comment]
> Can you please check if setting version to `>=18.2.0` will resolve the issue?

Sorry I never got back

So a couple of things:

1. I can't use anything lower than react 19rc for this framework
2. For my situation, I finally got things working by adding both mantine packages (core and hooks) to vite's optimizeDeps.exclude as well as ssr.noExternal options.
This was the only combination of settings that finally seemed to resolve the issue.

Tbh, I'm still at a loss to explain what the actual issue is and why this fixed it... but I agree with the comment above mine, the most common thread with all these issues looks to be related to RSC and/or the latest react versions. I think nextjs internally uses a canary react build

**Comment by thryothorus** [comment]
FWIW, @amatelski97 and I found that this "false error" showed up when using the mantine datepicker without having explicitly installed it.  It didn't throw an import error, which led us to think we already had it installed.

**Comment by romanesko** [comment]
if nothing works out for you, then maybe you made the same mistake as me:
I tried all the options described here, but everything turned out to be much simpler — I used LoadingOverlay in loading.tsx, and next does not pull up the layout for it, and accordingly loading took place without a MantineProvider

**Comment by sovetski** [comment]
Interesting, I had to remove the `package-json.lock` (mandatory) and remove `node_modules` then run `npm i` and it worked..

**Comment by sovetski** [comment]
Happened today again after installing the carousel here: https://mantine.dev/x/carousel/

**Comment by sovetski** [comment]
Same issue again and again... it happens everytime I update mantine to the latest version or even I install mantine plugins @rtivital this issue is definitely not resolved, just try to upgrade mantine or install its any plugin you will see the problem I think

**Comment by rtivital** [comment]
https://help.mantine.dev/q/mantine-provider-missing

**Comment by ravenberg** [comment]
I ran into this error fully convinced I was wrapping my component into the `MantineProvider`. But I was actually not.

```
export default function () {
  const theme = useMantineTheme();

  return (
    <AppLayout>
      <p style={{ color: theme.colors.blue[5] }}>Just an example</p>
    </AppLayout>
  )
}
```

If you are not careful you can easily think you have wrapped your component around MantineTheme in root components like NextJS's `page.tsx`;

```
page.tsx (calls useMantineTheme here -> FAILS because no Provider above it)
  └── AppLayout
       └── MantineProvider (Provider starts here)
            └── children (I intuitively assumed it was called here) 
```

Such a silly yet easy mistake to make.
