### ISSUE TITLE
use-form: errorMessages accept function

### ISSUE THREAD

**Issue by ruessej** [mantinedev/mantine#533]
### Usage example, including component/hook API

This is important when you want to show different errors.

For example, you want to check that the selected element of a Select is not undefined and item.active is true and want to show different error messages

**Comment by MartinMuzatko** [comment]
Related Discord discussion: https://discord.com/channels/854810300876062770/854810300876062773/921316151303225394

Would it be possible to provide functions for use-forms errorMessages? I want to display different information based on error. With e.g. zod I can get specific validation errors I would love to display.
You could provide better/specific context information this way 
Instead of generic "value is too big or too small"

### Prior Art
I'd draw inspiration from validation like e.g. quasar is doing, to provide context sensitive error messages.
https://quasar.dev/vue-components/input
```
// Array of Functions/Strings; If String, then it must be a name of one of the embedded validation rules
:rules="[ val => val.length <= 3 || 'Please use maximum 3 characters' ]"
```

Vuetify also does function based validation with error messages 🤔  https://vuetifyjs.com/en/components/text-fields/#validation
React final form also: http://jinno.io/app/14/?source=react-final-form 

### Breaking Change
it is a breaking change though, so I do not think we can add it as a part of minor release

I understand. This is also a reason why I proposed to extend errorMessages, but then the validationRules logic is duplicated, which is not nice.
Is it possible to make the validationRules to not break, if we allow returning either boolean or string? (Making the errorMessages  obsolete, when providing the error already via validationRules. Or wait for the next major release to make it right.

**Comment by ruessej** [comment]
What if we add a new property to the options where you combine errors and validation? And let this return boolean or a string.

And in a later version we can remove validationRules and errorMessages as a Breaking Change


```ts
validationError: {
   input: (val) => val === "Test" ? "Test is not valid" : true
}
```

**Comment by rtivital** [comment]
Implemented in `@mantine/form` package

**Comment by Saul-BT** [comment]
Hi @rtivital 

Can you specify exactly where is this implemented? (I think it's useful to have a reference linked to this issue)

The official docs at https://mantine.dev/form/use-form/ seems a bit outdated.

**Comment by rtivital** [comment]
Documentation is up to date – https://mantine.dev/form/use-form/#validation-with-rules-object
