### ISSUE TITLE
@mantine/core defaultvalue not working selected !

### ISSUE THREAD

**Issue by stuckkode** [mantinedev/mantine#5634]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

i',m edit data and im using mantine hook to set value form the select , this select not selected the default value  
<img width="1324" alt="Jepretan Layar 2024-01-25 pukul 09 12 39" src="https://github.com/mantinedev/mantine/assets/70086027/9362c0c3-fdb7-4dab-87b1-746bf9b66346">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by stuckkode** [comment]
but mantine v6 normal , so weird !! , i'm need using v7

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction. Template https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

**Comment by stuckkode** [comment]
okay nope , i'll tricked this bug hehe with api search for target

**Comment by stuckkode** [comment]
this case is
where if the default value select uses api from the server side pagination limit, the label doesn't appear, only the value appears, that's the problem here

**Comment by stuckkode** [comment]
please add append default value feature like select2 js :D

**Comment by msv96** [comment]
Hi @stuckkode, it will be really helpful for the maintainers and contributors to debug the issue when they have a sandbox which reproduces the same issue. So please create a minimal reproduction and share it here. Thanks.
Template - https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

**Comment by rtivital** [comment]
You are welcome to reopen the issue, if you can provide a reproduction.

**Comment by AlexeyEsin** [comment]
@rtivital I don't know if this is related to this issue, but I managed to reproduce the behavior when `Select` does not display the default value. This happens if the `data` is updated asynchronously (in my case, it comes from the backend). After the `data` was updated, the internal value of `Select` was also updated, which can be seen in React DevTools. However, the selected value is not displayed until you focus on `Select`. This is reproduced with both object options and strings.

https://codesandbox.io/p/sandbox/agitated-cloud-dmyzfl
