### ISSUE TITLE
NumberInput is changing value to string if number is more than 16 digits

### ISSUE THREAD

**Issue by SargoDev** [mantinedev/mantine#5650]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Hello

NumberInput is changing value to string if number is more than 16 digits

`<NumberInput value={value} onChange={(val) => setValue(val)}`

but when `<NumberInput value={value} onChange={(val) => setValue(parseInt(val))`

value for more than 16 digits it adds zeros at the end of value.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by SargoDev** [comment]
Furthermore, when I add a number and then delete it, the value is set to an empty string ('') instead of null or undefined, even when I set `defaultValue={undefined}`

**Comment by ozerenes** [comment]
It seems like the issue you're facing is related to the limitations of JavaScript's parseInt function, which may result in unexpected behavior for large numbers. The parseInt function in JavaScript is designed to handle 32-bit signed integers, and when dealing with numbers larger than Number.MAX_SAFE_INTEGER, precision can be lost.

To handle large numbers in your case, you might want to use the parseFloat function instead of parseInt since you are dealing with floating-point numbers. However, keep in mind that JavaScript also has limitations on the precision of floating-point numbers.

**Comment by SargoDev** [comment]
@ozerenes Thank you for your comment. You are right about that, but how can I handle the situation where the value is set to an empty string ('') when deleting input in the NumberInput? It really bothers me because I can't properly validate a field that is supposed to be a number or undefined, not a string.

**Comment by ozerenes** [comment]
You're welcome. I have examined the source code, it is difficult to decide whether undefined type will exist or not.

**Comment by rtivital** [comment]
- As mentioned above numbers that exceed `Number.MAX_SAFE_INTEGER` are represented as strings to avoid issues with the parsing algorithm
- NumberInput value is `string | number` type. You can perform additional checks and transforms on your side if needed. `undefined` is not a valid value, as it indicates that the component is uncontrolled.

The component works as intended in both cases
