### ISSUE TITLE
The minDate in Dates should be the default date, when date is not given

### ISSUE THREAD

**Issue by leonschwanitz** [mantinedev/mantine#5695]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When the DateInput property (minDate) is set to, for example, 2024-09-01, and the DateInput is controlled through the form but the date is undefined, I expect the calendar to automatically navigate to the correct month of the minDate. It can be confusing for the user when the min date is in the future (and the month is greyed out). Additionally, the defaultDate does not work properly when using the mantine/forms plugin.

### Possible fix

Start the default month (date) with the minDate given.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by michaelperros** [comment]
I've recreated this issue 

It seems to occur because [_finalValue](https://github.com/mantinedev/mantine/blob/e7d1c4b19305ea43b8c0ed9de92e3252d2469477/packages/%40mantine/dates/src/hooks/use-uncontrolled-dates/use-uncontrolled-dates.ts#L36) returns undefined until a date is selected, even if minDate has been set.

A solution would be to pass minDate to useUncontrolledDates and conditionally set _finalValue with minDate month.

If that sounds good I can work on a pr. Otherwise happy to revise based on your feedback.

Thanks

**Comment by rtivital** [comment]
Sounds fine, feel free to submit a pr

**Comment by michaelperros** [comment]
Please see #6646

This is different than my initial idea as mentioned above because it did not produce the desired results. However, this pr is a similar idea and also simpler.

This pr does not address the additional issue that @leonschwanitz mentioned at the end of their description. If they wish to submit another issue that is specific to that bug I'd be happy to take a look.
