### ISSUE TITLE
Combobox `readOnly` does not work

### ISSUE THREAD

**Issue by crabvk** [mantinedev/mantine#5764]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Setting `readOnly` property to `true` on `Combobox` component does not work, i.e. still can open the dropdown and change selected value.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-combobox-readonly-bug-pcjtnr

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by AlexisDominguez** [comment]
I'm facing a similar issue with the Select component. `readonly` attribute is always applied to the Select input, no matter if I have the read-only prop active or not.

This is causing me problems with styling, because I want to style some elements by using the readonly attribute, but because of this, those styles apply to all elements.

![image](https://github.com/mantinedev/mantine/assets/38707921/8b83e186-a09f-4970-8e7f-858ea87449a1)

**Comment by rtivital** [comment]
Combobox `readOnly` controls whether the value can be changed, not whether the dropdown state can be changed. Combobox is not an input, if you build a component with it and need to implement the `readOnly` logic in your component.

If you want to prevent dropdown from being opened, set `disabled` prop on Combobox instead.

**Comment by crabvk** [comment]
@rtivital 
> Combobox `readOnly` controls whether the value can be changed, not whether the dropdown state can be changed.

OK, but then, if you look at the example I provided, the value of Combobox **can be changed** regardless of `readOnly` prop value.

**Comment by rtivital** [comment]
Yes, I probably stated it wrong. Combobox is not an input. `readOnly` does not apply to it at all. This logic belongs to the input element or your component, depending on how you organize it.
