### ISSUE TITLE
Modals with portal target set are being rendered off screen

### ISSUE THREAD

**Issue by dryu** [mantinedev/mantine#5937]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When we set `portalProps={{ target: "#modal-root" }}` on a Modal, it is being rendered off screen and not visible to a user.

Use case: I have a `<form>` that must include the contents of a modal but I have to render modal as a child to it. By default, modal will be removed as a child and rendered to a new div appended to a body, but if I set portal target to it, then it is being rendered in the place I want, but I can't see it as it is off screen.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-fs-modal-bug-3z4mwz

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The modal is not visible because you've rendered it inside Stack and Group which are flex containers – unexpected styles are being applied to the modal content. If you move it to a regular div element, it works as expected – https://codesandbox.io/p/sandbox/mantine-fs-modal-bug-forked-74qz28?file=%2Fsrc%2FApp.tsx.
