### ISSUE TITLE
Small glitch when using a confirm modal without children

### ISSUE THREAD

**Issue by sebastien-prudhomme** [mantinedev/mantine#6324]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/modals

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Small visual glitch on the button focus when the confirm modal is not using children:

![image](https://github.com/mantinedev/mantine/assets/641962/68984a19-90f6-41ae-bf9e-6d8ae365fa01)

Sample code:

```
  const openResetConfirmModal = () => modals.openConfirmModal({
    centered: true,
    labels: {
      cancel: "Cancel",
      confirm: "Reset",
    },
    onConfirm: () => reset(),
    title: "Reset the form?",
    withCloseButton: false,
  });
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by stefanzmf** [comment]
This happens because of:
- modal header css has `z-index: 1000;` + some other css that overlaps everything
- highlighting button is done using `outline` so it is not taking space in box model but stays in place and it s getting overlapped by that header zindex 

Not sure if it really worth adding some logic to fix this (if it worth, please let me know). It can be fixed on the spot using 
```
groupProps: {
  style: { paddingTop: '4px' },
},
```

**Comment by Prasiddha22** [comment]
As we see there is the logic to add a margin bottom to the container wrapping the children. 
<img width="397" alt="Screenshot 2024-06-04 at 10 56 44 PM" src="https://github.com/mantinedev/mantine/assets/54320725/883cb918-2542-41e5-9652-ef847084c4c5">

As this is happening because of the modal header, when there is no children, there will not be `margin-bottom` ( present in the children container). So I think we might want to use the similar logic and add `margin-top` when there is no children just to level it up.
Please let me know if we differ in opinion.
