### ISSUE TITLE
Buttons or links not working in the combobox footer

### ISSUE THREAD

**Issue by TomDiekmann** [mantinedev/mantine#6335]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

If i use the Combobox component with a Dropdown Footer any Button or Link in this Footer is not clickable. I suspect the dropdown gets closed before components in the footer can trigger an onClick event.

This can be seen on the combobox examples page (https://mantine.dev/combobox/?e=DropdownFooter), where the Mantine link in the footer is not working.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by stefanzmf** [comment]
I have investigated the issue a bit. It happens because of this line `onBlur={() => store.closeDropdown()}` added to the `<TextInput` component. The same happens if you click on header too. 

One fix that I have in mind is to add `preventDefault()` on `onMouseDown` for both, `ComboboxFooter` and `ComboboxHeader` (basically the same approach form `ComboboxOptions`).  

```
      onMouseDown={(event) => {
        event?.preventDefault();
      }}
```

PS: I m new here and I would like to bring my contribution to mantine
