### ISSUE TITLE
Component Inside Appshell.Main cannot take full height of Appshell.Main

### ISSUE THREAD

**Issue by Justcallmesu** [mantinedev/mantine#6341]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using **Mantine Components** such as `Container` or` Center` inside the `Appshell.Main`, they cannot take the full height of the `Appshell.Main`, even though I have already set the style to {height: "100%"}. I have using the Mantine Appshell template [Mantine Appshell Example](https://mantine.dev/app-shell/?e=AltLayout&s=code) thinking i was doing something wrong, but the issue still persists.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by stefanzmf** [comment]
This is not related to the AppShell/Center or Container, but to the actual CSS behaviour. There are multiple ways of forcing this, but I guess the most straightforward one is to make use of flex: `<AppShell.Main style={{ display: "flex" }}>` should do the trick.

You need to be careful in the case you are adding more child elements to the `AppShell.Main` component since it can not meet your expectations until you don t play around with flex settings (`flexDirection: "column"` + a few more flex adjustments)

**Comment by Justcallmesu** [comment]
> This is not related to the AppShell/Center or Container, but to the actual CSS behaviour. There are multiple ways of forcing this, but I guess the most straightforward one is to make use of flex: `<AppShell.Main style={{ display: "flex" }}>` + `flex: "1 1 auto"` on direct child element should do the trick.
> 
> You need to be careful in the case you are adding more child elements to the `AppShell.Main` component since it can not meet your expectations until you don t play around with flex settings (`flexDirection: "column"` + a few more flex adjustments).
> 
> ```
>       <AppShell.Main style={{ display: "flex" }}>
>         <Container style={{ background: "red", flex: "1 1 auto" }}>
>           Main
>         </Container>
>       </AppShell.Main>
> ```

Wow this save my day, thank you for the help. this is working in my project.
