### ISSUE TITLE
override styles from createTheme

### ISSUE THREAD

**Issue by hadar888** [mantinedev/mantine#6361]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

i created default style using createTheme for Title component because most of the Title components in my project looks the same, but one of the have different style, so i tried to use emotion to set different style for that component but it seems that the style in the createTheme is overriding the style from the emotion and not vice versa like i expected.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-vlqnlf?file=%2Fsrc%2FApp.tsx%3A31%2C32

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This happens because you use two different methods of applying styles – https://codesandbox.io/p/sandbox/mantine-react-template-forked-rr6st9?file=%2Fsrc%2FApp.tsx%3A20%2C28
Mantine does not provide any features to manage priority of emotion styles across `@emotion/react` and `@emotion/styled`. You can either stick with `@emotion/react` package or figure out how to fix this issue with custom emotion cache (see emotion documentation, it is out of Mantine scope).
