### ISSUE TITLE
select searchable click outside

### ISSUE THREAD

**Issue by ofirgo1** [mantinedev/mantine#6363]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

when clicking outside of the browser after opening the select options (with searchable), the options disappear but if you clicks on the location where the options were, it will be selected.
on the other selects, when clicking outside of the browser after opening the select options (with searchable), the options stays in not disappear.

https://github.com/mantinedev/mantine/assets/152078954/e33cb2d0-f32e-4155-a381-e1c81c173ef8

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This happens because the dropdown is not visible when the element does not have focus. When you move the focus back to the browser window, it focuses the element that had focus before the browser lost focus. It is not planned to fix this issue – there is not any good way to change the logic of the dropdown opened state to incorporate this fix.
