### ISSUE TITLE
Image component  in Group component does not display  image on firefox

### ISSUE THREAD

**Issue by Kieferleiter** [mantinedev/mantine#6374]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Firefox

### Describe the bug

When using the `<Image>` component within a `<Group>` images are displayed correctly on chromium based browsers but not on firefox

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-xshq5c?file=%2Fsrc%2FApp.tsx%3A16%2C1

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The sandbox that you've sent is empty

**Comment by Kieferleiter** [comment]
> The sandbox that you've sent is empty

Sorry my mistake, I updated the link

**Comment by rtivital** [comment]
This is how flexbox works in Firefox. It is not planned to be fixed in the library. On your side , you can set `flex={1}` on the image component, `grow` on the Group component or use a different component for this use case – https://codesandbox.io/p/sandbox/mantine-react-template-forked-r2lxym?file=%2Fsrc%2FApp.tsx
