### ISSUE TITLE
Popover `onOpen` does not work with controlled state.

### ISSUE THREAD

**Issue by crabvk** [mantinedev/mantine#6981]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Using controlled state with `useDisclosure` and `onOpen` callback of Popover component.
The callback isn't being called.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/dh3ddv

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by truckcarr11** [comment]
Diving into the source code, it looks like this is intentional. Can see that [here](https://github.com/mantinedev/mantine/blob/e0721af0aafc7acf2c32aa5275633b218d2fc6af/packages/%40mantine/core/src/components/Popover/use-popover.ts#L163)

Only when the popover is un-controlled does it call the hooks for onOpen and onClose.

If I had to guess, it is because you can react to changes using useEffect. You can see an example of that [here](https://codesandbox.io/p/sandbox/mantine-popover-bug-forked-dxcwp4?workspaceId=8a7361d7-1071-42ce-8e5d-b6318f626917)

**Comment by crabvk** [comment]
The commit message says:
> Popover: Fix `onClose` function being called twice with controlled state

so, seems like `onClose` called somewhere else, but `onOpen` doesn't.
Looks strange 🤔
