### ISSUE TITLE
ScrollArea doesn't work in a dynamic height container

### ISSUE THREAD

**Issue by eakl** [mantinedev/mantine#724]
### What package has an issue

@mantine/core

### Describe the bug

`ScrollArea` doesn't work in a flex container when the parent is `flexGrow: 1` or `height: 100%`

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/eloquent-margulis-d7pv7?file=/src/Content.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
It works fine, you just need to remove a wrapper div – https://codesandbox.io/s/vigilant-roentgen-j4f9y?file=/src/Content.tsx

**Comment by eakl** [comment]
Why the wrapper div needs to be removed? on nested container, I can't make it work locally?

**Comment by rtivital** [comment]
I don't know, this is just how ScrollArea works

> I can't make it work locally

It should not be different from the example that I've provided in sandbox. We have the same logic in [Navabar.Section component](https://mantine.dev/core/app-shell/#navbar-with-custom-scrollbars) and Select/MultiSelect dropdowns, it works fine.

**Comment by rtivital** [comment]
If you have any other questions, feel free to ask them here or on Discord

**Comment by BoreasHe** [comment]
Hi, sorry for digging into the closed issue.
I found a trick to "solve" this weird issue:
```jsx
<Card>
  <Card.Section>
  // ...
  </Card.Section>

  // Relative wrapper
  <div style={{ position: "relative", height: "100%" }}>
    // Absolute scrollarea div, adjust the 0s if needed
    <ScrollArea style={{ position: "absolute", top: 0, bottom: 0, left: 0, right: 0 }}>
      {
        // mapping func
      }
    </ScrollArea>
  </div>
</Card>
```
It may not be an elegant solution, but hope it helps someone who encountered this problem.

**Comment by cole-themeta** [comment]
I can't get `ScrollArea` to work inside of a `Tabs.Tab` and nothing here helped me :/

**Comment by rtivital** [comment]
Tabs.Tab is not different from any other content, ScrollArea works fine – https://codesandbox.io/s/inspiring-gauss-7nphy3?file=/src/App.tsx

**Comment by cole-themeta** [comment]
Okay, let me clarify. I can get it to work with a set height, but I want it to take up 100% of it's parent and scroll in that. Setting height to `100%` or not setting it scrolls the entire page which is the issue I'm having here.

Tab 1 has a `400px` height and scrolls the parent, Tab 2 has a `100%` height and scrolls the entire page:
https://codesandbox.io/s/awesome-mopsa-2jnxhs?file=/src/App.tsx

**Comment by cole-themeta** [comment]
@rtivital Any ideas on this ^?

**Comment by rtivital** [comment]
I've provided all examples I had, the general approach is to wrap ScrollArea in flex container and setting `flex: 1` on it. You can find examples in previous sandboxes and Navbar.Section component source code as an example.

**Comment by cole-themeta** [comment]
@rtivital I've been working with a variety of different components over the last two weeks and everything else has worked without issue. 

The ONLY problematic component I've used in ScrollArea. I absolutely no matter what I do CANNOT get it to work with dynamic height content despite the working example above. Wrapping it in a flex container and setting `flex: 1` on the ScrollArea within does nothing (see codesandbox below).

And I just ran into another issue where it doesn't let you scroll if you set maxHeight instead of height which makes no sense to me. In this case, it just simply doesn't allow for scrolling at all.

See updated code sandbox for examples:
https://codesandbox.io/s/zealous-poitras-xftoqn?file=/src/App.tsx

The issue isn't just with Tabs.Tab or anything else specific, it's with ScrollArea itself, it simply doesn't seem to work in most cases.

**Comment by sarbull** [comment]
> The secret ingredient is setting the _calulated_ height of the above flex container which is an extremely important missed detail!
> 
> `height: "calc(100vh - 40px)"`
> 
> But it works! So all is good even if it took a good week to get there!

```
.your-wrapper {
  div[role="tabpanel"] {
    height: calc(100% - 40px);
    padding-top:0px;
  }
}
```

**Comment by paulgpeterson** [comment]
Here's another question for you. It looks like the above problems were solved by adding `height: "calc(100vh - 40px)"`, but this is still using a fixed height. Looking through the [Navbar.Section](https://mantine.dev/core/app-shell/#navbar-with-custom-scrollbars) example as well, the `<Navbar />` itself has a fixed height of `600`. 

My problem is that I want to have a ScrollArea within a dropdown that contains both a header (search bar, etc) and a footer (control / submit buttons), but I don't want to set a fixed height because the content in `<ScrollArea>` may not have enough items to fill said fixed height. It is looking like there is no way to use this component with containers, flex or otherwise, with truly dynamic height as opposed to fixed or calculated values.

**Comment by paulgpeterson** [comment]
[This question on Stack Overflow](https://stackoverflow.com/questions/10980822/scrollbar-without-fixed-height-dynamic-height-with-scrollbar) yielded a solution that helped me. Checkout the [JS Fiddle Example here](http://jsfiddle.net/xXJD25/wkpw8wcc/).

To solve my problem, I removed `<ScrollArea />` and used a `<Box />` with the following styles (as given by the JS Fiddle example):

```
overflow-y: auto;
height: auto;
max-height: 400px;
```

Now I can scroll that middle container with the header above and footer below staying in place.

**Comment by rtivital** [comment]
@paulgpeterson We provide `ScrollArea.Autosize` component that does the same thing – https://mantine.dev/core/scroll-area/#scrollareaautosize

**Comment by kevinbeal** [comment]
Max Height works fine when you wrap the `ScrollArea` in a div like `<div style={{maxHeight:400,display:"flex"}}><ScrollArea /></div>`

**Comment by rtivital** [comment]
There is a usage example in documentation

**Comment by wanghq-23** [comment]
How can I use AutoSize in Prism? I want to make the prism width grow when the parent is flexGrow: 1 or height: 100%. View width work well but i can't use view width in react-markdown componet render.Is there any way to solve this problem. Thanks!

**Comment by asyncink** [comment]
For anyone who is curious how to achieve `ScrollArea.Autosize` behavior bot for width:

```tsx
<ScrollArea
  w="min-content"
  maw="100%">
  ...
</ScrollArea>
```
