### ISSUE TITLE
Form in modal seems broken

### ISSUE THREAD

**Issue by PringlePot** [mantinedev/mantine#751]
### What package has an issue

@mantine/hooks

### Describe the bug

When creating a form within a modal, the textinput seems to glitch, when using it in codesandbox it doesnt seem to open an embed at all

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/compassionate-noether-03cd4?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
- It does not work in codesandbox because you are using `useModals` hook outside the `ModalsProvider` context
- Content modals cannot be used with dynamic children – once modal is opened, snapshot is saved into internal state and cannot be updated
- There are several options to handle dynamic content with modals:
  - [Use internal component state](https://codesandbox.io/s/romantic-cray-qhi2c?file=/src/App.tsx)
  - Use Modal component instead of modals manager

If you need any clarification, feel free to reach out here or on Discord.
