### ISSUE TITLE
Confirm Modal errors when labels not provided

### ISSUE THREAD

**Issue by mattrunyon** [mantinedev/mantine#836]
### What package has an issue

@mantine/modals

### Describe the bug

`openConfirmModal` does not require labels in the props, but errors if `labels`, `cancelProps`, and `confirmProps` are not provided

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/unruffled-boyd-fb1gk?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Provide default values for labels, check labels exists before reading `labels.confirm` and `labels.cancel`, or make labels a required prop

**Comment by iDavidB** [comment]
This is because you can set default labels on the ModalsProvider. 

See: [https://mantine.dev/others/modals/#confirm-modal](https://mantine.dev/others/modals/#confirm-modal)

Right above the "Context modals" heading. I think it would be good if it had its' own heading though, it's a little hard to find now.
