### ISSUE TITLE
`use-page-leave` calls twice when leaving the page through a scrollbar

### ISSUE THREAD

**Issue by Theboiboi8** [mantinedev/mantine#886]
### What package has an issue

@mantine/hooks

### Describe the bug

When using the `use-page-leave` hook, the assigned function gets called twice when leaving the page on the side of the page with the scrollbar (if there is one), once on hovering the scrollbar and once on actually leaving the browser window.

### In which browser did the problem occur

Opera 84.0.4316.14

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/eloquent-forest-9li7b7?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Detecting when the mouse is on the scrollbar, and making it so that `use-page-leave` does not trigger on mousing the scrollbar.

**Comment by rtivital** [comment]
@EmilMalanczak did you have a chance to explore this issue?

**Comment by SheharyarAnwar** [comment]
I have identified two issues in the usePageLeave hook. 

1. The usage of the variable `from` is incorrect. It refers to the opposite of the thing that is actually happening in that statement in my opinion.
 `event.relatedTarget` refers to the EventTarget the pointing device entered to after `mouseout`. That's why I would like to propose using variable `to` instead of `from`.
 
 2. `(!from || (from as any).nodeName === 'HTML')` will fire the the function twice. Once when the pointer enters the scrollbar i.e `html` and the second time when the pointer is outside of `html` and has no target that it enters in. 
 
 I think that the usage of `from` instead of `to` lead to this confusion.

**Comment by wes337** [comment]
Might want to try using `mouseleave` instead of `mouseout`. 

`mouseleave` is fired when the pointer exits the element and _all_ of its descendants, and `mouseout` fires when it leaves the element or _any_ one of it's descendants. In this case the scrollbar could be seen as a descendant. Also is there any point in trying to get the root HTML node from the event? Seems unnecessary.

@SheharyarAnwar your comment is about the variable name and doesn't actually address the issue.

**Comment by wes337** [comment]
The following change to the hook will resolve this:

```
  useEffect(() => {
    document.documentElement.addEventListener('mouseleave', onPageLeave);
    return () => document.documentElement.removeEventListener('mouseleave', onPageLeave);
  }, []);
```
