### ISSUE TITLE
adding scrollabel tabs with arrows [Feature Request] 

### ISSUE THREAD

**Issue by Mood-al** [mantinedev/mantine#929]
### Usage example, including component/hook API

Hey guys I would love to see scrollable tabs like mui scrollable  tabs with navigation arrows and way to customize them with RTL support

**Comment by rtivital** [comment]
Thanks for a feature request, it does not seem very useful, so we are not planning to add it as a part of the library

**Comment by congyaqwq** [comment]
In a simple way, we can use `ArrowLeft` or `ArrowRight`
Or, just use `scrollIntoView`
```
const StyledTab = (props: TabProps) => {

  const ref = useRef<HTMLButtonElement>(null);

  return (
    <Tabs.Tab
      ref={ref}
      {...props}
      onClick={(...args) => {
        props.onClick && props.onClick(...args);
        ref?.current?.scrollIntoView({ behavior: 'smooth', inline: 'center' });
      }}
    />
  );
};
```

**Comment by congyaqwq** [comment]
> 

```
<ScrollArea type="never">
    <Tabs.List>  { ... } </Tabs.List>
<ScrollArea>
```

**Comment by Mood-al** [comment]
Hey guys I'm going to close this issue 

I built a cutsom component for this.
You can check it out from here 
https://github.com/Mood-al/react-tabs-scrollable

**Comment by lucas-santosP** [comment]
This is a useful feature! MUI already [has it](https://mui.com/material-ui/react-tabs/#scrollable-tabs) and would be great if Mantine has it too. Which would improve Mantine as an MUI alternative.

And scrollable tabs are so much better for mobile layouts. The current "flex-wrap" behavior makes the layout look misaligned due to the different widths of the labels.

![image](https://user-images.githubusercontent.com/49699501/235275513-09f3c0e4-fb21-4e37-8950-a2c31403751a.png)
